// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videouploadservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videoupload "video-platform-microservice/rpc-videoUpload/kitex_gen/videoupload"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InitUpload(ctx context.Context, req *videoupload.InitUploadReq, callOptions ...callopt.Option) (r *videoupload.InitUploadResp, err error)
	UploadChunk(ctx context.Context, req *videoupload.UploadChunkReq, callOptions ...callopt.Option) (r *videoupload.UploadChunkResp, err error)
	FinalizeUpload(ctx context.Context, req *videoupload.FinalizeUploadReq, callOptions ...callopt.Option) (r *videoupload.FinalizeUploadResp, err error)
	SimpleUpload(ctx context.Context, req *videoupload.SimpleUploadReq, callOptions ...callopt.Option) (r *videoupload.SimpleUploadResp, err error)
	QueryProgress(ctx context.Context, req *videoupload.QueryProgressReq, callOptions ...callopt.Option) (r *videoupload.QueryProgressResp, err error)
	AbortUpload(ctx context.Context, req *videoupload.AbortUploadReq, callOptions ...callopt.Option) (r *videoupload.AbortUploadResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoUploadServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoUploadServiceClient struct {
	*kClient
}

func (p *kVideoUploadServiceClient) InitUpload(ctx context.Context, req *videoupload.InitUploadReq, callOptions ...callopt.Option) (r *videoupload.InitUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitUpload(ctx, req)
}

func (p *kVideoUploadServiceClient) UploadChunk(ctx context.Context, req *videoupload.UploadChunkReq, callOptions ...callopt.Option) (r *videoupload.UploadChunkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadChunk(ctx, req)
}

func (p *kVideoUploadServiceClient) FinalizeUpload(ctx context.Context, req *videoupload.FinalizeUploadReq, callOptions ...callopt.Option) (r *videoupload.FinalizeUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FinalizeUpload(ctx, req)
}

func (p *kVideoUploadServiceClient) SimpleUpload(ctx context.Context, req *videoupload.SimpleUploadReq, callOptions ...callopt.Option) (r *videoupload.SimpleUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SimpleUpload(ctx, req)
}

func (p *kVideoUploadServiceClient) QueryProgress(ctx context.Context, req *videoupload.QueryProgressReq, callOptions ...callopt.Option) (r *videoupload.QueryProgressResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryProgress(ctx, req)
}

func (p *kVideoUploadServiceClient) AbortUpload(ctx context.Context, req *videoupload.AbortUploadReq, callOptions ...callopt.Option) (r *videoupload.AbortUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AbortUpload(ctx, req)
}
