// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videouploadservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	videoupload "video-platform-microservice/rpc-videoUpload/kitex_gen/videoupload"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"InitUpload": kitex.NewMethodInfo(
		initUploadHandler,
		newVideoUploadServiceInitUploadArgs,
		newVideoUploadServiceInitUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadChunk": kitex.NewMethodInfo(
		uploadChunkHandler,
		newVideoUploadServiceUploadChunkArgs,
		newVideoUploadServiceUploadChunkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FinalizeUpload": kitex.NewMethodInfo(
		finalizeUploadHandler,
		newVideoUploadServiceFinalizeUploadArgs,
		newVideoUploadServiceFinalizeUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SimpleUpload": kitex.NewMethodInfo(
		simpleUploadHandler,
		newVideoUploadServiceSimpleUploadArgs,
		newVideoUploadServiceSimpleUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoUploadServiceServiceInfo                = NewServiceInfo()
	videoUploadServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoUploadServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoUploadServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoUploadServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoUploadServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoUploadService"
	handlerType := (*videoupload.VideoUploadService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "videoupload",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func initUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoupload.VideoUploadServiceInitUploadArgs)
	realResult := result.(*videoupload.VideoUploadServiceInitUploadResult)
	success, err := handler.(videoupload.VideoUploadService).InitUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoUploadServiceInitUploadArgs() interface{} {
	return videoupload.NewVideoUploadServiceInitUploadArgs()
}

func newVideoUploadServiceInitUploadResult() interface{} {
	return videoupload.NewVideoUploadServiceInitUploadResult()
}

func uploadChunkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoupload.VideoUploadServiceUploadChunkArgs)
	realResult := result.(*videoupload.VideoUploadServiceUploadChunkResult)
	success, err := handler.(videoupload.VideoUploadService).UploadChunk(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoUploadServiceUploadChunkArgs() interface{} {
	return videoupload.NewVideoUploadServiceUploadChunkArgs()
}

func newVideoUploadServiceUploadChunkResult() interface{} {
	return videoupload.NewVideoUploadServiceUploadChunkResult()
}

func finalizeUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoupload.VideoUploadServiceFinalizeUploadArgs)
	realResult := result.(*videoupload.VideoUploadServiceFinalizeUploadResult)
	success, err := handler.(videoupload.VideoUploadService).FinalizeUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoUploadServiceFinalizeUploadArgs() interface{} {
	return videoupload.NewVideoUploadServiceFinalizeUploadArgs()
}

func newVideoUploadServiceFinalizeUploadResult() interface{} {
	return videoupload.NewVideoUploadServiceFinalizeUploadResult()
}

func simpleUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videoupload.VideoUploadServiceSimpleUploadArgs)
	realResult := result.(*videoupload.VideoUploadServiceSimpleUploadResult)
	success, err := handler.(videoupload.VideoUploadService).SimpleUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoUploadServiceSimpleUploadArgs() interface{} {
	return videoupload.NewVideoUploadServiceSimpleUploadArgs()
}

func newVideoUploadServiceSimpleUploadResult() interface{} {
	return videoupload.NewVideoUploadServiceSimpleUploadResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) InitUpload(ctx context.Context, req *videoupload.InitUploadReq) (r *videoupload.InitUploadResp, err error) {
	var _args videoupload.VideoUploadServiceInitUploadArgs
	_args.Req = req
	var _result videoupload.VideoUploadServiceInitUploadResult
	if err = p.c.Call(ctx, "InitUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadChunk(ctx context.Context, req *videoupload.UploadChunkReq) (r *videoupload.UploadChunkResp, err error) {
	var _args videoupload.VideoUploadServiceUploadChunkArgs
	_args.Req = req
	var _result videoupload.VideoUploadServiceUploadChunkResult
	if err = p.c.Call(ctx, "UploadChunk", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FinalizeUpload(ctx context.Context, req *videoupload.FinalizeUploadReq) (r *videoupload.FinalizeUploadResp, err error) {
	var _args videoupload.VideoUploadServiceFinalizeUploadArgs
	_args.Req = req
	var _result videoupload.VideoUploadServiceFinalizeUploadResult
	if err = p.c.Call(ctx, "FinalizeUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SimpleUpload(ctx context.Context, req *videoupload.SimpleUploadReq) (r *videoupload.SimpleUploadResp, err error) {
	var _args videoupload.VideoUploadServiceSimpleUploadArgs
	_args.Req = req
	var _result videoupload.VideoUploadServiceSimpleUploadResult
	if err = p.c.Call(ctx, "SimpleUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
