// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package videoupload

import (
	"context"
	"fmt"
)

type InitUploadReq struct {
	FileHash  string  `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	Filename  *string `thrift:"filename,2,optional" frugal:"2,optional,string" json:"filename,omitempty"`
	FileSize  *int64  `thrift:"file_size,3,optional" frugal:"3,optional,i64" json:"file_size,omitempty"`
	UserId    *string `thrift:"user_id,4,optional" frugal:"4,optional,string" json:"user_id,omitempty"`
	Width     *int32  `thrift:"width,5,optional" frugal:"5,optional,i32" json:"width,omitempty"`
	Height    *int32  `thrift:"height,6,optional" frugal:"6,optional,i32" json:"height,omitempty"`
	RequestId *string `thrift:"request_id,7,optional" frugal:"7,optional,string" json:"request_id,omitempty"`
}

func NewInitUploadReq() *InitUploadReq {
	return &InitUploadReq{}
}

func (p *InitUploadReq) InitDefault() {
}

func (p *InitUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

var InitUploadReq_Filename_DEFAULT string

func (p *InitUploadReq) GetFilename() (v string) {
	if !p.IsSetFilename() {
		return InitUploadReq_Filename_DEFAULT
	}
	return *p.Filename
}

var InitUploadReq_FileSize_DEFAULT int64

func (p *InitUploadReq) GetFileSize() (v int64) {
	if !p.IsSetFileSize() {
		return InitUploadReq_FileSize_DEFAULT
	}
	return *p.FileSize
}

var InitUploadReq_UserId_DEFAULT string

func (p *InitUploadReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return InitUploadReq_UserId_DEFAULT
	}
	return *p.UserId
}

var InitUploadReq_Width_DEFAULT int32

func (p *InitUploadReq) GetWidth() (v int32) {
	if !p.IsSetWidth() {
		return InitUploadReq_Width_DEFAULT
	}
	return *p.Width
}

var InitUploadReq_Height_DEFAULT int32

func (p *InitUploadReq) GetHeight() (v int32) {
	if !p.IsSetHeight() {
		return InitUploadReq_Height_DEFAULT
	}
	return *p.Height
}

var InitUploadReq_RequestId_DEFAULT string

func (p *InitUploadReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return InitUploadReq_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *InitUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *InitUploadReq) SetFilename(val *string) {
	p.Filename = val
}
func (p *InitUploadReq) SetFileSize(val *int64) {
	p.FileSize = val
}
func (p *InitUploadReq) SetUserId(val *string) {
	p.UserId = val
}
func (p *InitUploadReq) SetWidth(val *int32) {
	p.Width = val
}
func (p *InitUploadReq) SetHeight(val *int32) {
	p.Height = val
}
func (p *InitUploadReq) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *InitUploadReq) IsSetFilename() bool {
	return p.Filename != nil
}

func (p *InitUploadReq) IsSetFileSize() bool {
	return p.FileSize != nil
}

func (p *InitUploadReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *InitUploadReq) IsSetWidth() bool {
	return p.Width != nil
}

func (p *InitUploadReq) IsSetHeight() bool {
	return p.Height != nil
}

func (p *InitUploadReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *InitUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadReq(%+v)", *p)
}

var fieldIDToName_InitUploadReq = map[int16]string{
	1: "file_hash",
	2: "filename",
	3: "file_size",
	4: "user_id",
	5: "width",
	6: "height",
	7: "request_id",
}

type InitUploadResp struct {
	Code           int32    `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg            string   `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Status         *string  `thrift:"status,3,optional" frugal:"3,optional,string" json:"status,omitempty"`
	Url            *string  `thrift:"url,4,optional" frugal:"4,optional,string" json:"url,omitempty"`
	FinishedChunks []string `thrift:"finished_chunks,5,optional" frugal:"5,optional,list<string>" json:"finished_chunks,omitempty"`
}

func NewInitUploadResp() *InitUploadResp {
	return &InitUploadResp{}
}

func (p *InitUploadResp) InitDefault() {
}

func (p *InitUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *InitUploadResp) GetMsg() (v string) {
	return p.Msg
}

var InitUploadResp_Status_DEFAULT string

func (p *InitUploadResp) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return InitUploadResp_Status_DEFAULT
	}
	return *p.Status
}

var InitUploadResp_Url_DEFAULT string

func (p *InitUploadResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return InitUploadResp_Url_DEFAULT
	}
	return *p.Url
}

var InitUploadResp_FinishedChunks_DEFAULT []string

func (p *InitUploadResp) GetFinishedChunks() (v []string) {
	if !p.IsSetFinishedChunks() {
		return InitUploadResp_FinishedChunks_DEFAULT
	}
	return p.FinishedChunks
}
func (p *InitUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *InitUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *InitUploadResp) SetStatus(val *string) {
	p.Status = val
}
func (p *InitUploadResp) SetUrl(val *string) {
	p.Url = val
}
func (p *InitUploadResp) SetFinishedChunks(val []string) {
	p.FinishedChunks = val
}

func (p *InitUploadResp) IsSetStatus() bool {
	return p.Status != nil
}

func (p *InitUploadResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *InitUploadResp) IsSetFinishedChunks() bool {
	return p.FinishedChunks != nil
}

func (p *InitUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadResp(%+v)", *p)
}

var fieldIDToName_InitUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "status",
	4: "url",
	5: "finished_chunks",
}

type UploadChunkReq struct {
	FileHash   string  `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	ChunkIndex int32   `thrift:"chunk_index,2,required" frugal:"2,required,i32" json:"chunk_index"`
	ChunkData  []byte  `thrift:"chunk_data,3,required" frugal:"3,required,binary" json:"chunk_data"`
	UserId     *string `thrift:"user_id,4,optional" frugal:"4,optional,string" json:"user_id,omitempty"`
	RequestId  *string `thrift:"request_id,5,optional" frugal:"5,optional,string" json:"request_id,omitempty"`
}

func NewUploadChunkReq() *UploadChunkReq {
	return &UploadChunkReq{}
}

func (p *UploadChunkReq) InitDefault() {
}

func (p *UploadChunkReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *UploadChunkReq) GetChunkIndex() (v int32) {
	return p.ChunkIndex
}

func (p *UploadChunkReq) GetChunkData() (v []byte) {
	return p.ChunkData
}

var UploadChunkReq_UserId_DEFAULT string

func (p *UploadChunkReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return UploadChunkReq_UserId_DEFAULT
	}
	return *p.UserId
}

var UploadChunkReq_RequestId_DEFAULT string

func (p *UploadChunkReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return UploadChunkReq_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *UploadChunkReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *UploadChunkReq) SetChunkIndex(val int32) {
	p.ChunkIndex = val
}
func (p *UploadChunkReq) SetChunkData(val []byte) {
	p.ChunkData = val
}
func (p *UploadChunkReq) SetUserId(val *string) {
	p.UserId = val
}
func (p *UploadChunkReq) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *UploadChunkReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *UploadChunkReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *UploadChunkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadChunkReq(%+v)", *p)
}

var fieldIDToName_UploadChunkReq = map[int16]string{
	1: "file_hash",
	2: "chunk_index",
	3: "chunk_data",
	4: "user_id",
	5: "request_id",
}

type UploadChunkResp struct {
	Code            int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg             string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	AlreadyUploaded *bool  `thrift:"already_uploaded,3,optional" frugal:"3,optional,bool" json:"already_uploaded,omitempty"`
}

func NewUploadChunkResp() *UploadChunkResp {
	return &UploadChunkResp{}
}

func (p *UploadChunkResp) InitDefault() {
}

func (p *UploadChunkResp) GetCode() (v int32) {
	return p.Code
}

func (p *UploadChunkResp) GetMsg() (v string) {
	return p.Msg
}

var UploadChunkResp_AlreadyUploaded_DEFAULT bool

func (p *UploadChunkResp) GetAlreadyUploaded() (v bool) {
	if !p.IsSetAlreadyUploaded() {
		return UploadChunkResp_AlreadyUploaded_DEFAULT
	}
	return *p.AlreadyUploaded
}
func (p *UploadChunkResp) SetCode(val int32) {
	p.Code = val
}
func (p *UploadChunkResp) SetMsg(val string) {
	p.Msg = val
}
func (p *UploadChunkResp) SetAlreadyUploaded(val *bool) {
	p.AlreadyUploaded = val
}

func (p *UploadChunkResp) IsSetAlreadyUploaded() bool {
	return p.AlreadyUploaded != nil
}

func (p *UploadChunkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadChunkResp(%+v)", *p)
}

var fieldIDToName_UploadChunkResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "already_uploaded",
}

type FinalizeUploadReq struct {
	FileHash    string   `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	Filename    string   `thrift:"filename,2,required" frugal:"2,required,string" json:"filename"`
	TotalChunks int32    `thrift:"total_chunks,3,required" frugal:"3,required,i32" json:"total_chunks"`
	UserId      *string  `thrift:"user_id,4,optional" frugal:"4,optional,string" json:"user_id,omitempty"`
	Width       *int32   `thrift:"width,5,optional" frugal:"5,optional,i32" json:"width,omitempty"`
	Height      *int32   `thrift:"height,6,optional" frugal:"6,optional,i32" json:"height,omitempty"`
	RequestId   *string  `thrift:"request_id,7,optional" frugal:"7,optional,string" json:"request_id,omitempty"`
	Resolutions []string `thrift:"resolutions,8,optional" frugal:"8,optional,list<string>" json:"resolutions,omitempty"`
}

func NewFinalizeUploadReq() *FinalizeUploadReq {
	return &FinalizeUploadReq{}
}

func (p *FinalizeUploadReq) InitDefault() {
}

func (p *FinalizeUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *FinalizeUploadReq) GetFilename() (v string) {
	return p.Filename
}

func (p *FinalizeUploadReq) GetTotalChunks() (v int32) {
	return p.TotalChunks
}

var FinalizeUploadReq_UserId_DEFAULT string

func (p *FinalizeUploadReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return FinalizeUploadReq_UserId_DEFAULT
	}
	return *p.UserId
}

var FinalizeUploadReq_Width_DEFAULT int32

func (p *FinalizeUploadReq) GetWidth() (v int32) {
	if !p.IsSetWidth() {
		return FinalizeUploadReq_Width_DEFAULT
	}
	return *p.Width
}

var FinalizeUploadReq_Height_DEFAULT int32

func (p *FinalizeUploadReq) GetHeight() (v int32) {
	if !p.IsSetHeight() {
		return FinalizeUploadReq_Height_DEFAULT
	}
	return *p.Height
}

var FinalizeUploadReq_RequestId_DEFAULT string

func (p *FinalizeUploadReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return FinalizeUploadReq_RequestId_DEFAULT
	}
	return *p.RequestId
}

var FinalizeUploadReq_Resolutions_DEFAULT []string

func (p *FinalizeUploadReq) GetResolutions() (v []string) {
	if !p.IsSetResolutions() {
		return FinalizeUploadReq_Resolutions_DEFAULT
	}
	return p.Resolutions
}
func (p *FinalizeUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *FinalizeUploadReq) SetFilename(val string) {
	p.Filename = val
}
func (p *FinalizeUploadReq) SetTotalChunks(val int32) {
	p.TotalChunks = val
}
func (p *FinalizeUploadReq) SetUserId(val *string) {
	p.UserId = val
}
func (p *FinalizeUploadReq) SetWidth(val *int32) {
	p.Width = val
}
func (p *FinalizeUploadReq) SetHeight(val *int32) {
	p.Height = val
}
func (p *FinalizeUploadReq) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *FinalizeUploadReq) SetResolutions(val []string) {
	p.Resolutions = val
}

func (p *FinalizeUploadReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *FinalizeUploadReq) IsSetWidth() bool {
	return p.Width != nil
}

func (p *FinalizeUploadReq) IsSetHeight() bool {
	return p.Height != nil
}

func (p *FinalizeUploadReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *FinalizeUploadReq) IsSetResolutions() bool {
	return p.Resolutions != nil
}

func (p *FinalizeUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinalizeUploadReq(%+v)", *p)
}

var fieldIDToName_FinalizeUploadReq = map[int16]string{
	1: "file_hash",
	2: "filename",
	3: "total_chunks",
	4: "user_id",
	5: "width",
	6: "height",
	7: "request_id",
	8: "resolutions",
}

type FinalizeUploadResp struct {
	Code   int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg    string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Url    *string `thrift:"url,3,optional" frugal:"3,optional,string" json:"url,omitempty"`
	TaskId *string `thrift:"task_id,4,optional" frugal:"4,optional,string" json:"task_id,omitempty"`
}

func NewFinalizeUploadResp() *FinalizeUploadResp {
	return &FinalizeUploadResp{}
}

func (p *FinalizeUploadResp) InitDefault() {
}

func (p *FinalizeUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *FinalizeUploadResp) GetMsg() (v string) {
	return p.Msg
}

var FinalizeUploadResp_Url_DEFAULT string

func (p *FinalizeUploadResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return FinalizeUploadResp_Url_DEFAULT
	}
	return *p.Url
}

var FinalizeUploadResp_TaskId_DEFAULT string

func (p *FinalizeUploadResp) GetTaskId() (v string) {
	if !p.IsSetTaskId() {
		return FinalizeUploadResp_TaskId_DEFAULT
	}
	return *p.TaskId
}
func (p *FinalizeUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *FinalizeUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *FinalizeUploadResp) SetUrl(val *string) {
	p.Url = val
}
func (p *FinalizeUploadResp) SetTaskId(val *string) {
	p.TaskId = val
}

func (p *FinalizeUploadResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *FinalizeUploadResp) IsSetTaskId() bool {
	return p.TaskId != nil
}

func (p *FinalizeUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinalizeUploadResp(%+v)", *p)
}

var fieldIDToName_FinalizeUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "url",
	4: "task_id",
}

type SimpleUploadReq struct {
	FileData []byte  `thrift:"file_data,1,required" frugal:"1,required,binary" json:"file_data"`
	Filename string  `thrift:"filename,2,required" frugal:"2,required,string" json:"filename"`
	FileHash string  `thrift:"file_hash,3,required" frugal:"3,required,string" json:"file_hash"`
	UserId   *string `thrift:"user_id,4,optional" frugal:"4,optional,string" json:"user_id,omitempty"`
}

func NewSimpleUploadReq() *SimpleUploadReq {
	return &SimpleUploadReq{}
}

func (p *SimpleUploadReq) InitDefault() {
}

func (p *SimpleUploadReq) GetFileData() (v []byte) {
	return p.FileData
}

func (p *SimpleUploadReq) GetFilename() (v string) {
	return p.Filename
}

func (p *SimpleUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

var SimpleUploadReq_UserId_DEFAULT string

func (p *SimpleUploadReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return SimpleUploadReq_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *SimpleUploadReq) SetFileData(val []byte) {
	p.FileData = val
}
func (p *SimpleUploadReq) SetFilename(val string) {
	p.Filename = val
}
func (p *SimpleUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *SimpleUploadReq) SetUserId(val *string) {
	p.UserId = val
}

func (p *SimpleUploadReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *SimpleUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SimpleUploadReq(%+v)", *p)
}

var fieldIDToName_SimpleUploadReq = map[int16]string{
	1: "file_data",
	2: "filename",
	3: "file_hash",
	4: "user_id",
}

type SimpleUploadResp struct {
	Code int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Url  *string `thrift:"url,3,optional" frugal:"3,optional,string" json:"url,omitempty"`
}

func NewSimpleUploadResp() *SimpleUploadResp {
	return &SimpleUploadResp{}
}

func (p *SimpleUploadResp) InitDefault() {
}

func (p *SimpleUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *SimpleUploadResp) GetMsg() (v string) {
	return p.Msg
}

var SimpleUploadResp_Url_DEFAULT string

func (p *SimpleUploadResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return SimpleUploadResp_Url_DEFAULT
	}
	return *p.Url
}
func (p *SimpleUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *SimpleUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *SimpleUploadResp) SetUrl(val *string) {
	p.Url = val
}

func (p *SimpleUploadResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *SimpleUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SimpleUploadResp(%+v)", *p)
}

var fieldIDToName_SimpleUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "url",
}

type VideoUploadService interface {
	InitUpload(ctx context.Context, req *InitUploadReq) (r *InitUploadResp, err error)

	UploadChunk(ctx context.Context, req *UploadChunkReq) (r *UploadChunkResp, err error)

	FinalizeUpload(ctx context.Context, req *FinalizeUploadReq) (r *FinalizeUploadResp, err error)

	SimpleUpload(ctx context.Context, req *SimpleUploadReq) (r *SimpleUploadResp, err error)
}

type VideoUploadServiceInitUploadArgs struct {
	Req *InitUploadReq `thrift:"req,1" frugal:"1,default,InitUploadReq" json:"req"`
}

func NewVideoUploadServiceInitUploadArgs() *VideoUploadServiceInitUploadArgs {
	return &VideoUploadServiceInitUploadArgs{}
}

func (p *VideoUploadServiceInitUploadArgs) InitDefault() {
}

var VideoUploadServiceInitUploadArgs_Req_DEFAULT *InitUploadReq

func (p *VideoUploadServiceInitUploadArgs) GetReq() (v *InitUploadReq) {
	if !p.IsSetReq() {
		return VideoUploadServiceInitUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoUploadServiceInitUploadArgs) SetReq(val *InitUploadReq) {
	p.Req = val
}

func (p *VideoUploadServiceInitUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoUploadServiceInitUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceInitUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceInitUploadArgs = map[int16]string{
	1: "req",
}

type VideoUploadServiceInitUploadResult struct {
	Success *InitUploadResp `thrift:"success,0,optional" frugal:"0,optional,InitUploadResp" json:"success,omitempty"`
}

func NewVideoUploadServiceInitUploadResult() *VideoUploadServiceInitUploadResult {
	return &VideoUploadServiceInitUploadResult{}
}

func (p *VideoUploadServiceInitUploadResult) InitDefault() {
}

var VideoUploadServiceInitUploadResult_Success_DEFAULT *InitUploadResp

func (p *VideoUploadServiceInitUploadResult) GetSuccess() (v *InitUploadResp) {
	if !p.IsSetSuccess() {
		return VideoUploadServiceInitUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoUploadServiceInitUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*InitUploadResp)
}

func (p *VideoUploadServiceInitUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoUploadServiceInitUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceInitUploadResult(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceInitUploadResult = map[int16]string{
	0: "success",
}

type VideoUploadServiceUploadChunkArgs struct {
	Req *UploadChunkReq `thrift:"req,1" frugal:"1,default,UploadChunkReq" json:"req"`
}

func NewVideoUploadServiceUploadChunkArgs() *VideoUploadServiceUploadChunkArgs {
	return &VideoUploadServiceUploadChunkArgs{}
}

func (p *VideoUploadServiceUploadChunkArgs) InitDefault() {
}

var VideoUploadServiceUploadChunkArgs_Req_DEFAULT *UploadChunkReq

func (p *VideoUploadServiceUploadChunkArgs) GetReq() (v *UploadChunkReq) {
	if !p.IsSetReq() {
		return VideoUploadServiceUploadChunkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoUploadServiceUploadChunkArgs) SetReq(val *UploadChunkReq) {
	p.Req = val
}

func (p *VideoUploadServiceUploadChunkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoUploadServiceUploadChunkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceUploadChunkArgs(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceUploadChunkArgs = map[int16]string{
	1: "req",
}

type VideoUploadServiceUploadChunkResult struct {
	Success *UploadChunkResp `thrift:"success,0,optional" frugal:"0,optional,UploadChunkResp" json:"success,omitempty"`
}

func NewVideoUploadServiceUploadChunkResult() *VideoUploadServiceUploadChunkResult {
	return &VideoUploadServiceUploadChunkResult{}
}

func (p *VideoUploadServiceUploadChunkResult) InitDefault() {
}

var VideoUploadServiceUploadChunkResult_Success_DEFAULT *UploadChunkResp

func (p *VideoUploadServiceUploadChunkResult) GetSuccess() (v *UploadChunkResp) {
	if !p.IsSetSuccess() {
		return VideoUploadServiceUploadChunkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoUploadServiceUploadChunkResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadChunkResp)
}

func (p *VideoUploadServiceUploadChunkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoUploadServiceUploadChunkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceUploadChunkResult(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceUploadChunkResult = map[int16]string{
	0: "success",
}

type VideoUploadServiceFinalizeUploadArgs struct {
	Req *FinalizeUploadReq `thrift:"req,1" frugal:"1,default,FinalizeUploadReq" json:"req"`
}

func NewVideoUploadServiceFinalizeUploadArgs() *VideoUploadServiceFinalizeUploadArgs {
	return &VideoUploadServiceFinalizeUploadArgs{}
}

func (p *VideoUploadServiceFinalizeUploadArgs) InitDefault() {
}

var VideoUploadServiceFinalizeUploadArgs_Req_DEFAULT *FinalizeUploadReq

func (p *VideoUploadServiceFinalizeUploadArgs) GetReq() (v *FinalizeUploadReq) {
	if !p.IsSetReq() {
		return VideoUploadServiceFinalizeUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoUploadServiceFinalizeUploadArgs) SetReq(val *FinalizeUploadReq) {
	p.Req = val
}

func (p *VideoUploadServiceFinalizeUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoUploadServiceFinalizeUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceFinalizeUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceFinalizeUploadArgs = map[int16]string{
	1: "req",
}

type VideoUploadServiceFinalizeUploadResult struct {
	Success *FinalizeUploadResp `thrift:"success,0,optional" frugal:"0,optional,FinalizeUploadResp" json:"success,omitempty"`
}

func NewVideoUploadServiceFinalizeUploadResult() *VideoUploadServiceFinalizeUploadResult {
	return &VideoUploadServiceFinalizeUploadResult{}
}

func (p *VideoUploadServiceFinalizeUploadResult) InitDefault() {
}

var VideoUploadServiceFinalizeUploadResult_Success_DEFAULT *FinalizeUploadResp

func (p *VideoUploadServiceFinalizeUploadResult) GetSuccess() (v *FinalizeUploadResp) {
	if !p.IsSetSuccess() {
		return VideoUploadServiceFinalizeUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoUploadServiceFinalizeUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*FinalizeUploadResp)
}

func (p *VideoUploadServiceFinalizeUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoUploadServiceFinalizeUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceFinalizeUploadResult(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceFinalizeUploadResult = map[int16]string{
	0: "success",
}

type VideoUploadServiceSimpleUploadArgs struct {
	Req *SimpleUploadReq `thrift:"req,1" frugal:"1,default,SimpleUploadReq" json:"req"`
}

func NewVideoUploadServiceSimpleUploadArgs() *VideoUploadServiceSimpleUploadArgs {
	return &VideoUploadServiceSimpleUploadArgs{}
}

func (p *VideoUploadServiceSimpleUploadArgs) InitDefault() {
}

var VideoUploadServiceSimpleUploadArgs_Req_DEFAULT *SimpleUploadReq

func (p *VideoUploadServiceSimpleUploadArgs) GetReq() (v *SimpleUploadReq) {
	if !p.IsSetReq() {
		return VideoUploadServiceSimpleUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoUploadServiceSimpleUploadArgs) SetReq(val *SimpleUploadReq) {
	p.Req = val
}

func (p *VideoUploadServiceSimpleUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoUploadServiceSimpleUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceSimpleUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceSimpleUploadArgs = map[int16]string{
	1: "req",
}

type VideoUploadServiceSimpleUploadResult struct {
	Success *SimpleUploadResp `thrift:"success,0,optional" frugal:"0,optional,SimpleUploadResp" json:"success,omitempty"`
}

func NewVideoUploadServiceSimpleUploadResult() *VideoUploadServiceSimpleUploadResult {
	return &VideoUploadServiceSimpleUploadResult{}
}

func (p *VideoUploadServiceSimpleUploadResult) InitDefault() {
}

var VideoUploadServiceSimpleUploadResult_Success_DEFAULT *SimpleUploadResp

func (p *VideoUploadServiceSimpleUploadResult) GetSuccess() (v *SimpleUploadResp) {
	if !p.IsSetSuccess() {
		return VideoUploadServiceSimpleUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoUploadServiceSimpleUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*SimpleUploadResp)
}

func (p *VideoUploadServiceSimpleUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoUploadServiceSimpleUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoUploadServiceSimpleUploadResult(%+v)", *p)
}

var fieldIDToName_VideoUploadServiceSimpleUploadResult = map[int16]string{
	0: "success",
}
