// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package videotranscode

import (
	"context"
	"fmt"
)

type TranscodeTaskReq struct {
	FileHash       string   `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	MinioUrl       string   `thrift:"minio_url,2,required" frugal:"2,required,string" json:"minio_url"`
	ResolutionList []string `thrift:"resolution_list,3,required" frugal:"3,required,list<string>" json:"resolution_list"`
}

func NewTranscodeTaskReq() *TranscodeTaskReq {
	return &TranscodeTaskReq{}
}

func (p *TranscodeTaskReq) InitDefault() {
}

func (p *TranscodeTaskReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *TranscodeTaskReq) GetMinioUrl() (v string) {
	return p.MinioUrl
}

func (p *TranscodeTaskReq) GetResolutionList() (v []string) {
	return p.ResolutionList
}
func (p *TranscodeTaskReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *TranscodeTaskReq) SetMinioUrl(val string) {
	p.MinioUrl = val
}
func (p *TranscodeTaskReq) SetResolutionList(val []string) {
	p.ResolutionList = val
}

func (p *TranscodeTaskReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeTaskReq(%+v)", *p)
}

var fieldIDToName_TranscodeTaskReq = map[int16]string{
	1: "file_hash",
	2: "minio_url",
	3: "resolution_list",
}

type TranscodeTaskResp struct {
	Code   int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg    string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	TaskId *string `thrift:"task_id,3,optional" frugal:"3,optional,string" json:"task_id,omitempty"`
}

func NewTranscodeTaskResp() *TranscodeTaskResp {
	return &TranscodeTaskResp{}
}

func (p *TranscodeTaskResp) InitDefault() {
}

func (p *TranscodeTaskResp) GetCode() (v int32) {
	return p.Code
}

func (p *TranscodeTaskResp) GetMsg() (v string) {
	return p.Msg
}

var TranscodeTaskResp_TaskId_DEFAULT string

func (p *TranscodeTaskResp) GetTaskId() (v string) {
	if !p.IsSetTaskId() {
		return TranscodeTaskResp_TaskId_DEFAULT
	}
	return *p.TaskId
}
func (p *TranscodeTaskResp) SetCode(val int32) {
	p.Code = val
}
func (p *TranscodeTaskResp) SetMsg(val string) {
	p.Msg = val
}
func (p *TranscodeTaskResp) SetTaskId(val *string) {
	p.TaskId = val
}

func (p *TranscodeTaskResp) IsSetTaskId() bool {
	return p.TaskId != nil
}

func (p *TranscodeTaskResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeTaskResp(%+v)", *p)
}

var fieldIDToName_TranscodeTaskResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "task_id",
}

type TranscodeStatusReq struct {
	TaskId string `thrift:"task_id,1,required" frugal:"1,required,string" json:"task_id"`
}

func NewTranscodeStatusReq() *TranscodeStatusReq {
	return &TranscodeStatusReq{}
}

func (p *TranscodeStatusReq) InitDefault() {
}

func (p *TranscodeStatusReq) GetTaskId() (v string) {
	return p.TaskId
}
func (p *TranscodeStatusReq) SetTaskId(val string) {
	p.TaskId = val
}

func (p *TranscodeStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeStatusReq(%+v)", *p)
}

var fieldIDToName_TranscodeStatusReq = map[int16]string{
	1: "task_id",
}

type TranscodeStatusResp struct {
	Code     int32    `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg      string   `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Status   *string  `thrift:"status,3,optional" frugal:"3,optional,string" json:"status,omitempty"`
	Progress *int32   `thrift:"progress,4,optional" frugal:"4,optional,i32" json:"progress,omitempty"`
	Urls     []string `thrift:"urls,5,optional" frugal:"5,optional,list<string>" json:"urls,omitempty"`
	ErrorMsg *string  `thrift:"error_msg,6,optional" frugal:"6,optional,string" json:"error_msg,omitempty"`
}

func NewTranscodeStatusResp() *TranscodeStatusResp {
	return &TranscodeStatusResp{}
}

func (p *TranscodeStatusResp) InitDefault() {
}

func (p *TranscodeStatusResp) GetCode() (v int32) {
	return p.Code
}

func (p *TranscodeStatusResp) GetMsg() (v string) {
	return p.Msg
}

var TranscodeStatusResp_Status_DEFAULT string

func (p *TranscodeStatusResp) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return TranscodeStatusResp_Status_DEFAULT
	}
	return *p.Status
}

var TranscodeStatusResp_Progress_DEFAULT int32

func (p *TranscodeStatusResp) GetProgress() (v int32) {
	if !p.IsSetProgress() {
		return TranscodeStatusResp_Progress_DEFAULT
	}
	return *p.Progress
}

var TranscodeStatusResp_Urls_DEFAULT []string

func (p *TranscodeStatusResp) GetUrls() (v []string) {
	if !p.IsSetUrls() {
		return TranscodeStatusResp_Urls_DEFAULT
	}
	return p.Urls
}

var TranscodeStatusResp_ErrorMsg_DEFAULT string

func (p *TranscodeStatusResp) GetErrorMsg() (v string) {
	if !p.IsSetErrorMsg() {
		return TranscodeStatusResp_ErrorMsg_DEFAULT
	}
	return *p.ErrorMsg
}
func (p *TranscodeStatusResp) SetCode(val int32) {
	p.Code = val
}
func (p *TranscodeStatusResp) SetMsg(val string) {
	p.Msg = val
}
func (p *TranscodeStatusResp) SetStatus(val *string) {
	p.Status = val
}
func (p *TranscodeStatusResp) SetProgress(val *int32) {
	p.Progress = val
}
func (p *TranscodeStatusResp) SetUrls(val []string) {
	p.Urls = val
}
func (p *TranscodeStatusResp) SetErrorMsg(val *string) {
	p.ErrorMsg = val
}

func (p *TranscodeStatusResp) IsSetStatus() bool {
	return p.Status != nil
}

func (p *TranscodeStatusResp) IsSetProgress() bool {
	return p.Progress != nil
}

func (p *TranscodeStatusResp) IsSetUrls() bool {
	return p.Urls != nil
}

func (p *TranscodeStatusResp) IsSetErrorMsg() bool {
	return p.ErrorMsg != nil
}

func (p *TranscodeStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeStatusResp(%+v)", *p)
}

var fieldIDToName_TranscodeStatusResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "status",
	4: "progress",
	5: "urls",
	6: "error_msg",
}

type VideoTranscodeService interface {
	CreateTask(ctx context.Context, req *TranscodeTaskReq) (r *TranscodeTaskResp, err error)

	GetStatus(ctx context.Context, req *TranscodeStatusReq) (r *TranscodeStatusResp, err error)
}

type VideoTranscodeServiceCreateTaskArgs struct {
	Req *TranscodeTaskReq `thrift:"req,1" frugal:"1,default,TranscodeTaskReq" json:"req"`
}

func NewVideoTranscodeServiceCreateTaskArgs() *VideoTranscodeServiceCreateTaskArgs {
	return &VideoTranscodeServiceCreateTaskArgs{}
}

func (p *VideoTranscodeServiceCreateTaskArgs) InitDefault() {
}

var VideoTranscodeServiceCreateTaskArgs_Req_DEFAULT *TranscodeTaskReq

func (p *VideoTranscodeServiceCreateTaskArgs) GetReq() (v *TranscodeTaskReq) {
	if !p.IsSetReq() {
		return VideoTranscodeServiceCreateTaskArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoTranscodeServiceCreateTaskArgs) SetReq(val *TranscodeTaskReq) {
	p.Req = val
}

func (p *VideoTranscodeServiceCreateTaskArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoTranscodeServiceCreateTaskArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoTranscodeServiceCreateTaskArgs(%+v)", *p)
}

var fieldIDToName_VideoTranscodeServiceCreateTaskArgs = map[int16]string{
	1: "req",
}

type VideoTranscodeServiceCreateTaskResult struct {
	Success *TranscodeTaskResp `thrift:"success,0,optional" frugal:"0,optional,TranscodeTaskResp" json:"success,omitempty"`
}

func NewVideoTranscodeServiceCreateTaskResult() *VideoTranscodeServiceCreateTaskResult {
	return &VideoTranscodeServiceCreateTaskResult{}
}

func (p *VideoTranscodeServiceCreateTaskResult) InitDefault() {
}

var VideoTranscodeServiceCreateTaskResult_Success_DEFAULT *TranscodeTaskResp

func (p *VideoTranscodeServiceCreateTaskResult) GetSuccess() (v *TranscodeTaskResp) {
	if !p.IsSetSuccess() {
		return VideoTranscodeServiceCreateTaskResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoTranscodeServiceCreateTaskResult) SetSuccess(x interface{}) {
	p.Success = x.(*TranscodeTaskResp)
}

func (p *VideoTranscodeServiceCreateTaskResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoTranscodeServiceCreateTaskResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoTranscodeServiceCreateTaskResult(%+v)", *p)
}

var fieldIDToName_VideoTranscodeServiceCreateTaskResult = map[int16]string{
	0: "success",
}

type VideoTranscodeServiceGetStatusArgs struct {
	Req *TranscodeStatusReq `thrift:"req,1" frugal:"1,default,TranscodeStatusReq" json:"req"`
}

func NewVideoTranscodeServiceGetStatusArgs() *VideoTranscodeServiceGetStatusArgs {
	return &VideoTranscodeServiceGetStatusArgs{}
}

func (p *VideoTranscodeServiceGetStatusArgs) InitDefault() {
}

var VideoTranscodeServiceGetStatusArgs_Req_DEFAULT *TranscodeStatusReq

func (p *VideoTranscodeServiceGetStatusArgs) GetReq() (v *TranscodeStatusReq) {
	if !p.IsSetReq() {
		return VideoTranscodeServiceGetStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoTranscodeServiceGetStatusArgs) SetReq(val *TranscodeStatusReq) {
	p.Req = val
}

func (p *VideoTranscodeServiceGetStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoTranscodeServiceGetStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoTranscodeServiceGetStatusArgs(%+v)", *p)
}

var fieldIDToName_VideoTranscodeServiceGetStatusArgs = map[int16]string{
	1: "req",
}

type VideoTranscodeServiceGetStatusResult struct {
	Success *TranscodeStatusResp `thrift:"success,0,optional" frugal:"0,optional,TranscodeStatusResp" json:"success,omitempty"`
}

func NewVideoTranscodeServiceGetStatusResult() *VideoTranscodeServiceGetStatusResult {
	return &VideoTranscodeServiceGetStatusResult{}
}

func (p *VideoTranscodeServiceGetStatusResult) InitDefault() {
}

var VideoTranscodeServiceGetStatusResult_Success_DEFAULT *TranscodeStatusResp

func (p *VideoTranscodeServiceGetStatusResult) GetSuccess() (v *TranscodeStatusResp) {
	if !p.IsSetSuccess() {
		return VideoTranscodeServiceGetStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoTranscodeServiceGetStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*TranscodeStatusResp)
}

func (p *VideoTranscodeServiceGetStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoTranscodeServiceGetStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoTranscodeServiceGetStatusResult(%+v)", *p)
}

var fieldIDToName_VideoTranscodeServiceGetStatusResult = map[int16]string{
	0: "success",
}
