// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videoservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	video "video-platform-microservice/gateway/kitex_gen/video"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"InitUpload": kitex.NewMethodInfo(
		initUploadHandler,
		newVideoServiceInitUploadArgs,
		newVideoServiceInitUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadChunk": kitex.NewMethodInfo(
		uploadChunkHandler,
		newVideoServiceUploadChunkArgs,
		newVideoServiceUploadChunkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MergeFile": kitex.NewMethodInfo(
		mergeFileHandler,
		newVideoServiceMergeFileArgs,
		newVideoServiceMergeFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DownloadChunk": kitex.NewMethodInfo(
		downloadChunkHandler,
		newVideoServiceDownloadChunkArgs,
		newVideoServiceDownloadChunkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoInfo": kitex.NewMethodInfo(
		getVideoInfoHandler,
		newVideoServiceGetVideoInfoArgs,
		newVideoServiceGetVideoInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Transcode": kitex.NewMethodInfo(
		transcodeHandler,
		newVideoServiceTranscodeArgs,
		newVideoServiceTranscodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTranscodeStatus": kitex.NewMethodInfo(
		getTranscodeStatusHandler,
		newVideoServiceGetTranscodeStatusArgs,
		newVideoServiceGetTranscodeStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoServiceServiceInfo                = NewServiceInfo()
	videoServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoService"
	handlerType := (*video.VideoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func initUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceInitUploadArgs)
	realResult := result.(*video.VideoServiceInitUploadResult)
	success, err := handler.(video.VideoService).InitUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceInitUploadArgs() interface{} {
	return video.NewVideoServiceInitUploadArgs()
}

func newVideoServiceInitUploadResult() interface{} {
	return video.NewVideoServiceInitUploadResult()
}

func uploadChunkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceUploadChunkArgs)
	realResult := result.(*video.VideoServiceUploadChunkResult)
	success, err := handler.(video.VideoService).UploadChunk(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceUploadChunkArgs() interface{} {
	return video.NewVideoServiceUploadChunkArgs()
}

func newVideoServiceUploadChunkResult() interface{} {
	return video.NewVideoServiceUploadChunkResult()
}

func mergeFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceMergeFileArgs)
	realResult := result.(*video.VideoServiceMergeFileResult)
	success, err := handler.(video.VideoService).MergeFile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceMergeFileArgs() interface{} {
	return video.NewVideoServiceMergeFileArgs()
}

func newVideoServiceMergeFileResult() interface{} {
	return video.NewVideoServiceMergeFileResult()
}

func downloadChunkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceDownloadChunkArgs)
	realResult := result.(*video.VideoServiceDownloadChunkResult)
	success, err := handler.(video.VideoService).DownloadChunk(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceDownloadChunkArgs() interface{} {
	return video.NewVideoServiceDownloadChunkArgs()
}

func newVideoServiceDownloadChunkResult() interface{} {
	return video.NewVideoServiceDownloadChunkResult()
}

func getVideoInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetVideoInfoArgs)
	realResult := result.(*video.VideoServiceGetVideoInfoResult)
	success, err := handler.(video.VideoService).GetVideoInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetVideoInfoArgs() interface{} {
	return video.NewVideoServiceGetVideoInfoArgs()
}

func newVideoServiceGetVideoInfoResult() interface{} {
	return video.NewVideoServiceGetVideoInfoResult()
}

func transcodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceTranscodeArgs)
	realResult := result.(*video.VideoServiceTranscodeResult)
	success, err := handler.(video.VideoService).Transcode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceTranscodeArgs() interface{} {
	return video.NewVideoServiceTranscodeArgs()
}

func newVideoServiceTranscodeResult() interface{} {
	return video.NewVideoServiceTranscodeResult()
}

func getTranscodeStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*video.VideoServiceGetTranscodeStatusArgs)
	realResult := result.(*video.VideoServiceGetTranscodeStatusResult)
	success, err := handler.(video.VideoService).GetTranscodeStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoServiceGetTranscodeStatusArgs() interface{} {
	return video.NewVideoServiceGetTranscodeStatusArgs()
}

func newVideoServiceGetTranscodeStatusResult() interface{} {
	return video.NewVideoServiceGetTranscodeStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) InitUpload(ctx context.Context, req *video.InitUploadReq) (r *video.InitUploadResp, err error) {
	var _args video.VideoServiceInitUploadArgs
	_args.Req = req
	var _result video.VideoServiceInitUploadResult
	if err = p.c.Call(ctx, "InitUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadChunk(ctx context.Context, req *video.UploadChunkReq) (r *video.UploadChunkResp, err error) {
	var _args video.VideoServiceUploadChunkArgs
	_args.Req = req
	var _result video.VideoServiceUploadChunkResult
	if err = p.c.Call(ctx, "UploadChunk", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MergeFile(ctx context.Context, req *video.MergeFileReq) (r *video.MergeFileResp, err error) {
	var _args video.VideoServiceMergeFileArgs
	_args.Req = req
	var _result video.VideoServiceMergeFileResult
	if err = p.c.Call(ctx, "MergeFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DownloadChunk(ctx context.Context, req *video.DownloadChunkReq) (r *video.DownloadChunkResp, err error) {
	var _args video.VideoServiceDownloadChunkArgs
	_args.Req = req
	var _result video.VideoServiceDownloadChunkResult
	if err = p.c.Call(ctx, "DownloadChunk", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoInfo(ctx context.Context, req *video.GetVideoInfoReq) (r *video.GetVideoInfoResp, err error) {
	var _args video.VideoServiceGetVideoInfoArgs
	_args.Req = req
	var _result video.VideoServiceGetVideoInfoResult
	if err = p.c.Call(ctx, "GetVideoInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Transcode(ctx context.Context, req *video.TranscodeReq) (r *video.TranscodeResp, err error) {
	var _args video.VideoServiceTranscodeArgs
	_args.Req = req
	var _result video.VideoServiceTranscodeResult
	if err = p.c.Call(ctx, "Transcode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTranscodeStatus(ctx context.Context, req *video.GetTranscodeStatusReq) (r *video.GetTranscodeStatusResp, err error) {
	var _args video.VideoServiceGetTranscodeStatusArgs
	_args.Req = req
	var _result video.VideoServiceGetTranscodeStatusResult
	if err = p.c.Call(ctx, "GetTranscodeStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
