// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videotranscodeservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videotranscode "video-platform-microservice/rpc-videoTranscode/kitex_gen/videotranscode"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTask(ctx context.Context, req *videotranscode.TranscodeTaskReq, callOptions ...callopt.Option) (r *videotranscode.TranscodeTaskResp, err error)
	GetStatus(ctx context.Context, req *videotranscode.TranscodeStatusReq, callOptions ...callopt.Option) (r *videotranscode.TranscodeStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoTranscodeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoTranscodeServiceClient struct {
	*kClient
}

func (p *kVideoTranscodeServiceClient) CreateTask(ctx context.Context, req *videotranscode.TranscodeTaskReq, callOptions ...callopt.Option) (r *videotranscode.TranscodeTaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTask(ctx, req)
}

func (p *kVideoTranscodeServiceClient) GetStatus(ctx context.Context, req *videotranscode.TranscodeStatusReq, callOptions ...callopt.Option) (r *videotranscode.TranscodeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStatus(ctx, req)
}
