// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videotranscodeservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	videotranscode "video-platform-microservice/rpc-videoTranscode/kitex_gen/videotranscode"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateTask": kitex.NewMethodInfo(
		createTaskHandler,
		newVideoTranscodeServiceCreateTaskArgs,
		newVideoTranscodeServiceCreateTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetStatus": kitex.NewMethodInfo(
		getStatusHandler,
		newVideoTranscodeServiceGetStatusArgs,
		newVideoTranscodeServiceGetStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoTranscodeServiceServiceInfo                = NewServiceInfo()
	videoTranscodeServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoTranscodeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoTranscodeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoTranscodeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoTranscodeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoTranscodeService"
	handlerType := (*videotranscode.VideoTranscodeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "videotranscode",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videotranscode.VideoTranscodeServiceCreateTaskArgs)
	realResult := result.(*videotranscode.VideoTranscodeServiceCreateTaskResult)
	success, err := handler.(videotranscode.VideoTranscodeService).CreateTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoTranscodeServiceCreateTaskArgs() interface{} {
	return videotranscode.NewVideoTranscodeServiceCreateTaskArgs()
}

func newVideoTranscodeServiceCreateTaskResult() interface{} {
	return videotranscode.NewVideoTranscodeServiceCreateTaskResult()
}

func getStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videotranscode.VideoTranscodeServiceGetStatusArgs)
	realResult := result.(*videotranscode.VideoTranscodeServiceGetStatusResult)
	success, err := handler.(videotranscode.VideoTranscodeService).GetStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoTranscodeServiceGetStatusArgs() interface{} {
	return videotranscode.NewVideoTranscodeServiceGetStatusArgs()
}

func newVideoTranscodeServiceGetStatusResult() interface{} {
	return videotranscode.NewVideoTranscodeServiceGetStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateTask(ctx context.Context, req *videotranscode.TranscodeTaskReq) (r *videotranscode.TranscodeTaskResp, err error) {
	var _args videotranscode.VideoTranscodeServiceCreateTaskArgs
	_args.Req = req
	var _result videotranscode.VideoTranscodeServiceCreateTaskResult
	if err = p.c.Call(ctx, "CreateTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetStatus(ctx context.Context, req *videotranscode.TranscodeStatusReq) (r *videotranscode.TranscodeStatusResp, err error) {
	var _args videotranscode.VideoTranscodeServiceGetStatusArgs
	_args.Req = req
	var _result videotranscode.VideoTranscodeServiceGetStatusResult
	if err = p.c.Call(ctx, "GetStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
