// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "video-platform-microservice/rpc-video/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InitUpload(ctx context.Context, req *video.InitUploadReq, callOptions ...callopt.Option) (r *video.InitUploadResp, err error)
	UploadChunk(ctx context.Context, req *video.UploadChunkReq, callOptions ...callopt.Option) (r *video.UploadChunkResp, err error)
	MergeFile(ctx context.Context, req *video.MergeFileReq, callOptions ...callopt.Option) (r *video.MergeFileResp, err error)
	DownloadChunk(ctx context.Context, req *video.DownloadChunkReq, callOptions ...callopt.Option) (r *video.DownloadChunkResp, err error)
	GetVideoInfo(ctx context.Context, req *video.GetVideoInfoReq, callOptions ...callopt.Option) (r *video.GetVideoInfoResp, err error)
	Transcode(ctx context.Context, req *video.TranscodeReq, callOptions ...callopt.Option) (r *video.TranscodeResp, err error)
	GetTranscodeStatus(ctx context.Context, req *video.GetTranscodeStatusReq, callOptions ...callopt.Option) (r *video.GetTranscodeStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) InitUpload(ctx context.Context, req *video.InitUploadReq, callOptions ...callopt.Option) (r *video.InitUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitUpload(ctx, req)
}

func (p *kVideoServiceClient) UploadChunk(ctx context.Context, req *video.UploadChunkReq, callOptions ...callopt.Option) (r *video.UploadChunkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadChunk(ctx, req)
}

func (p *kVideoServiceClient) MergeFile(ctx context.Context, req *video.MergeFileReq, callOptions ...callopt.Option) (r *video.MergeFileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MergeFile(ctx, req)
}

func (p *kVideoServiceClient) DownloadChunk(ctx context.Context, req *video.DownloadChunkReq, callOptions ...callopt.Option) (r *video.DownloadChunkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DownloadChunk(ctx, req)
}

func (p *kVideoServiceClient) GetVideoInfo(ctx context.Context, req *video.GetVideoInfoReq, callOptions ...callopt.Option) (r *video.GetVideoInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoInfo(ctx, req)
}

func (p *kVideoServiceClient) Transcode(ctx context.Context, req *video.TranscodeReq, callOptions ...callopt.Option) (r *video.TranscodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Transcode(ctx, req)
}

func (p *kVideoServiceClient) GetTranscodeStatus(ctx context.Context, req *video.GetTranscodeStatusReq, callOptions ...callopt.Option) (r *video.GetTranscodeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTranscodeStatus(ctx, req)
}
