// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package videomanager

import (
	"context"
	"fmt"
)

type InitUploadReq struct {
	FileHash  string  `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	Filename  string  `thrift:"filename,2,required" frugal:"2,required,string" json:"filename"`
	FileSize  int64   `thrift:"file_size,3,required" frugal:"3,required,i64" json:"file_size"`
	UserId    string  `thrift:"user_id,4,required" frugal:"4,required,string" json:"user_id"`
	Width     *int32  `thrift:"width,5,optional" frugal:"5,optional,i32" json:"width,omitempty"`
	Height    *int32  `thrift:"height,6,optional" frugal:"6,optional,i32" json:"height,omitempty"`
	RequestId *string `thrift:"request_id,7,optional" frugal:"7,optional,string" json:"request_id,omitempty"`
}

func NewInitUploadReq() *InitUploadReq {
	return &InitUploadReq{}
}

func (p *InitUploadReq) InitDefault() {
}

func (p *InitUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *InitUploadReq) GetFilename() (v string) {
	return p.Filename
}

func (p *InitUploadReq) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *InitUploadReq) GetUserId() (v string) {
	return p.UserId
}

var InitUploadReq_Width_DEFAULT int32

func (p *InitUploadReq) GetWidth() (v int32) {
	if !p.IsSetWidth() {
		return InitUploadReq_Width_DEFAULT
	}
	return *p.Width
}

var InitUploadReq_Height_DEFAULT int32

func (p *InitUploadReq) GetHeight() (v int32) {
	if !p.IsSetHeight() {
		return InitUploadReq_Height_DEFAULT
	}
	return *p.Height
}

var InitUploadReq_RequestId_DEFAULT string

func (p *InitUploadReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return InitUploadReq_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *InitUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *InitUploadReq) SetFilename(val string) {
	p.Filename = val
}
func (p *InitUploadReq) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *InitUploadReq) SetUserId(val string) {
	p.UserId = val
}
func (p *InitUploadReq) SetWidth(val *int32) {
	p.Width = val
}
func (p *InitUploadReq) SetHeight(val *int32) {
	p.Height = val
}
func (p *InitUploadReq) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *InitUploadReq) IsSetWidth() bool {
	return p.Width != nil
}

func (p *InitUploadReq) IsSetHeight() bool {
	return p.Height != nil
}

func (p *InitUploadReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *InitUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadReq(%+v)", *p)
}

var fieldIDToName_InitUploadReq = map[int16]string{
	1: "file_hash",
	2: "filename",
	3: "file_size",
	4: "user_id",
	5: "width",
	6: "height",
	7: "request_id",
}

type InitUploadResp struct {
	Code           int32    `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg            string   `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Status         *string  `thrift:"status,3,optional" frugal:"3,optional,string" json:"status,omitempty"`
	FinishedChunks []string `thrift:"finished_chunks,4,optional" frugal:"4,optional,list<string>" json:"finished_chunks,omitempty"`
	Url            *string  `thrift:"url,5,optional" frugal:"5,optional,string" json:"url,omitempty"`
	UploadId       *string  `thrift:"upload_id,6,optional" frugal:"6,optional,string" json:"upload_id,omitempty"`
}

func NewInitUploadResp() *InitUploadResp {
	return &InitUploadResp{}
}

func (p *InitUploadResp) InitDefault() {
}

func (p *InitUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *InitUploadResp) GetMsg() (v string) {
	return p.Msg
}

var InitUploadResp_Status_DEFAULT string

func (p *InitUploadResp) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return InitUploadResp_Status_DEFAULT
	}
	return *p.Status
}

var InitUploadResp_FinishedChunks_DEFAULT []string

func (p *InitUploadResp) GetFinishedChunks() (v []string) {
	if !p.IsSetFinishedChunks() {
		return InitUploadResp_FinishedChunks_DEFAULT
	}
	return p.FinishedChunks
}

var InitUploadResp_Url_DEFAULT string

func (p *InitUploadResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return InitUploadResp_Url_DEFAULT
	}
	return *p.Url
}

var InitUploadResp_UploadId_DEFAULT string

func (p *InitUploadResp) GetUploadId() (v string) {
	if !p.IsSetUploadId() {
		return InitUploadResp_UploadId_DEFAULT
	}
	return *p.UploadId
}
func (p *InitUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *InitUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *InitUploadResp) SetStatus(val *string) {
	p.Status = val
}
func (p *InitUploadResp) SetFinishedChunks(val []string) {
	p.FinishedChunks = val
}
func (p *InitUploadResp) SetUrl(val *string) {
	p.Url = val
}
func (p *InitUploadResp) SetUploadId(val *string) {
	p.UploadId = val
}

func (p *InitUploadResp) IsSetStatus() bool {
	return p.Status != nil
}

func (p *InitUploadResp) IsSetFinishedChunks() bool {
	return p.FinishedChunks != nil
}

func (p *InitUploadResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *InitUploadResp) IsSetUploadId() bool {
	return p.UploadId != nil
}

func (p *InitUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadResp(%+v)", *p)
}

var fieldIDToName_InitUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "status",
	4: "finished_chunks",
	5: "url",
	6: "upload_id",
}

type FinalizeUploadReq struct {
	FileHash    string   `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	Filename    string   `thrift:"filename,2,required" frugal:"2,required,string" json:"filename"`
	TotalChunks int32    `thrift:"total_chunks,3,required" frugal:"3,required,i32" json:"total_chunks"`
	UserId      string   `thrift:"user_id,4,required" frugal:"4,required,string" json:"user_id"`
	Width       *int32   `thrift:"width,5,optional" frugal:"5,optional,i32" json:"width,omitempty"`
	Height      *int32   `thrift:"height,6,optional" frugal:"6,optional,i32" json:"height,omitempty"`
	RequestId   *string  `thrift:"request_id,7,optional" frugal:"7,optional,string" json:"request_id,omitempty"`
	Resolutions []string `thrift:"resolutions,8,optional" frugal:"8,optional,list<string>" json:"resolutions,omitempty"`
	UploadId    *string  `thrift:"upload_id,9,optional" frugal:"9,optional,string" json:"upload_id,omitempty"`
}

func NewFinalizeUploadReq() *FinalizeUploadReq {
	return &FinalizeUploadReq{}
}

func (p *FinalizeUploadReq) InitDefault() {
}

func (p *FinalizeUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *FinalizeUploadReq) GetFilename() (v string) {
	return p.Filename
}

func (p *FinalizeUploadReq) GetTotalChunks() (v int32) {
	return p.TotalChunks
}

func (p *FinalizeUploadReq) GetUserId() (v string) {
	return p.UserId
}

var FinalizeUploadReq_Width_DEFAULT int32

func (p *FinalizeUploadReq) GetWidth() (v int32) {
	if !p.IsSetWidth() {
		return FinalizeUploadReq_Width_DEFAULT
	}
	return *p.Width
}

var FinalizeUploadReq_Height_DEFAULT int32

func (p *FinalizeUploadReq) GetHeight() (v int32) {
	if !p.IsSetHeight() {
		return FinalizeUploadReq_Height_DEFAULT
	}
	return *p.Height
}

var FinalizeUploadReq_RequestId_DEFAULT string

func (p *FinalizeUploadReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return FinalizeUploadReq_RequestId_DEFAULT
	}
	return *p.RequestId
}

var FinalizeUploadReq_Resolutions_DEFAULT []string

func (p *FinalizeUploadReq) GetResolutions() (v []string) {
	if !p.IsSetResolutions() {
		return FinalizeUploadReq_Resolutions_DEFAULT
	}
	return p.Resolutions
}

var FinalizeUploadReq_UploadId_DEFAULT string

func (p *FinalizeUploadReq) GetUploadId() (v string) {
	if !p.IsSetUploadId() {
		return FinalizeUploadReq_UploadId_DEFAULT
	}
	return *p.UploadId
}
func (p *FinalizeUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *FinalizeUploadReq) SetFilename(val string) {
	p.Filename = val
}
func (p *FinalizeUploadReq) SetTotalChunks(val int32) {
	p.TotalChunks = val
}
func (p *FinalizeUploadReq) SetUserId(val string) {
	p.UserId = val
}
func (p *FinalizeUploadReq) SetWidth(val *int32) {
	p.Width = val
}
func (p *FinalizeUploadReq) SetHeight(val *int32) {
	p.Height = val
}
func (p *FinalizeUploadReq) SetRequestId(val *string) {
	p.RequestId = val
}
func (p *FinalizeUploadReq) SetResolutions(val []string) {
	p.Resolutions = val
}
func (p *FinalizeUploadReq) SetUploadId(val *string) {
	p.UploadId = val
}

func (p *FinalizeUploadReq) IsSetWidth() bool {
	return p.Width != nil
}

func (p *FinalizeUploadReq) IsSetHeight() bool {
	return p.Height != nil
}

func (p *FinalizeUploadReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *FinalizeUploadReq) IsSetResolutions() bool {
	return p.Resolutions != nil
}

func (p *FinalizeUploadReq) IsSetUploadId() bool {
	return p.UploadId != nil
}

func (p *FinalizeUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinalizeUploadReq(%+v)", *p)
}

var fieldIDToName_FinalizeUploadReq = map[int16]string{
	1: "file_hash",
	2: "filename",
	3: "total_chunks",
	4: "user_id",
	5: "width",
	6: "height",
	7: "request_id",
	8: "resolutions",
	9: "upload_id",
}

type FinalizeUploadResp struct {
	Code   int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg    string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Url    *string `thrift:"url,3,optional" frugal:"3,optional,string" json:"url,omitempty"`
	TaskId *string `thrift:"task_id,4,optional" frugal:"4,optional,string" json:"task_id,omitempty"`
}

func NewFinalizeUploadResp() *FinalizeUploadResp {
	return &FinalizeUploadResp{}
}

func (p *FinalizeUploadResp) InitDefault() {
}

func (p *FinalizeUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *FinalizeUploadResp) GetMsg() (v string) {
	return p.Msg
}

var FinalizeUploadResp_Url_DEFAULT string

func (p *FinalizeUploadResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return FinalizeUploadResp_Url_DEFAULT
	}
	return *p.Url
}

var FinalizeUploadResp_TaskId_DEFAULT string

func (p *FinalizeUploadResp) GetTaskId() (v string) {
	if !p.IsSetTaskId() {
		return FinalizeUploadResp_TaskId_DEFAULT
	}
	return *p.TaskId
}
func (p *FinalizeUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *FinalizeUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *FinalizeUploadResp) SetUrl(val *string) {
	p.Url = val
}
func (p *FinalizeUploadResp) SetTaskId(val *string) {
	p.TaskId = val
}

func (p *FinalizeUploadResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *FinalizeUploadResp) IsSetTaskId() bool {
	return p.TaskId != nil
}

func (p *FinalizeUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FinalizeUploadResp(%+v)", *p)
}

var fieldIDToName_FinalizeUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "url",
	4: "task_id",
}

type QueryUploadProgressReq struct {
	UploadId string `thrift:"upload_id,1,required" frugal:"1,required,string" json:"upload_id"`
}

func NewQueryUploadProgressReq() *QueryUploadProgressReq {
	return &QueryUploadProgressReq{}
}

func (p *QueryUploadProgressReq) InitDefault() {
}

func (p *QueryUploadProgressReq) GetUploadId() (v string) {
	return p.UploadId
}
func (p *QueryUploadProgressReq) SetUploadId(val string) {
	p.UploadId = val
}

func (p *QueryUploadProgressReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUploadProgressReq(%+v)", *p)
}

var fieldIDToName_QueryUploadProgressReq = map[int16]string{
	1: "upload_id",
}

type QueryUploadProgressResp struct {
	Code          int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg           string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	UploadedParts *int32 `thrift:"uploaded_parts,3,optional" frugal:"3,optional,i32" json:"uploaded_parts,omitempty"`
	TotalParts    *int32 `thrift:"total_parts,4,optional" frugal:"4,optional,i32" json:"total_parts,omitempty"`
}

func NewQueryUploadProgressResp() *QueryUploadProgressResp {
	return &QueryUploadProgressResp{}
}

func (p *QueryUploadProgressResp) InitDefault() {
}

func (p *QueryUploadProgressResp) GetCode() (v int32) {
	return p.Code
}

func (p *QueryUploadProgressResp) GetMsg() (v string) {
	return p.Msg
}

var QueryUploadProgressResp_UploadedParts_DEFAULT int32

func (p *QueryUploadProgressResp) GetUploadedParts() (v int32) {
	if !p.IsSetUploadedParts() {
		return QueryUploadProgressResp_UploadedParts_DEFAULT
	}
	return *p.UploadedParts
}

var QueryUploadProgressResp_TotalParts_DEFAULT int32

func (p *QueryUploadProgressResp) GetTotalParts() (v int32) {
	if !p.IsSetTotalParts() {
		return QueryUploadProgressResp_TotalParts_DEFAULT
	}
	return *p.TotalParts
}
func (p *QueryUploadProgressResp) SetCode(val int32) {
	p.Code = val
}
func (p *QueryUploadProgressResp) SetMsg(val string) {
	p.Msg = val
}
func (p *QueryUploadProgressResp) SetUploadedParts(val *int32) {
	p.UploadedParts = val
}
func (p *QueryUploadProgressResp) SetTotalParts(val *int32) {
	p.TotalParts = val
}

func (p *QueryUploadProgressResp) IsSetUploadedParts() bool {
	return p.UploadedParts != nil
}

func (p *QueryUploadProgressResp) IsSetTotalParts() bool {
	return p.TotalParts != nil
}

func (p *QueryUploadProgressResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryUploadProgressResp(%+v)", *p)
}

var fieldIDToName_QueryUploadProgressResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "uploaded_parts",
	4: "total_parts",
}

type AbortUploadReq struct {
	UploadId string `thrift:"upload_id,1,required" frugal:"1,required,string" json:"upload_id"`
	FileHash string `thrift:"file_hash,2,required" frugal:"2,required,string" json:"file_hash"`
}

func NewAbortUploadReq() *AbortUploadReq {
	return &AbortUploadReq{}
}

func (p *AbortUploadReq) InitDefault() {
}

func (p *AbortUploadReq) GetUploadId() (v string) {
	return p.UploadId
}

func (p *AbortUploadReq) GetFileHash() (v string) {
	return p.FileHash
}
func (p *AbortUploadReq) SetUploadId(val string) {
	p.UploadId = val
}
func (p *AbortUploadReq) SetFileHash(val string) {
	p.FileHash = val
}

func (p *AbortUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AbortUploadReq(%+v)", *p)
}

var fieldIDToName_AbortUploadReq = map[int16]string{
	1: "upload_id",
	2: "file_hash",
}

type AbortUploadResp struct {
	Code int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
}

func NewAbortUploadResp() *AbortUploadResp {
	return &AbortUploadResp{}
}

func (p *AbortUploadResp) InitDefault() {
}

func (p *AbortUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *AbortUploadResp) GetMsg() (v string) {
	return p.Msg
}
func (p *AbortUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *AbortUploadResp) SetMsg(val string) {
	p.Msg = val
}

func (p *AbortUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AbortUploadResp(%+v)", *p)
}

var fieldIDToName_AbortUploadResp = map[int16]string{
	1: "code",
	2: "msg",
}

type GetVideoInfoReq struct {
	FileHash string  `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	UserId   *string `thrift:"user_id,2,optional" frugal:"2,optional,string" json:"user_id,omitempty"`
}

func NewGetVideoInfoReq() *GetVideoInfoReq {
	return &GetVideoInfoReq{}
}

func (p *GetVideoInfoReq) InitDefault() {
}

func (p *GetVideoInfoReq) GetFileHash() (v string) {
	return p.FileHash
}

var GetVideoInfoReq_UserId_DEFAULT string

func (p *GetVideoInfoReq) GetUserId() (v string) {
	if !p.IsSetUserId() {
		return GetVideoInfoReq_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *GetVideoInfoReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *GetVideoInfoReq) SetUserId(val *string) {
	p.UserId = val
}

func (p *GetVideoInfoReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *GetVideoInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoInfoReq(%+v)", *p)
}

var fieldIDToName_GetVideoInfoReq = map[int16]string{
	1: "file_hash",
	2: "user_id",
}

type GetVideoInfoResp struct {
	Code            int32    `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg             string   `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	FileHash        *string  `thrift:"file_hash,3,optional" frugal:"3,optional,string" json:"file_hash,omitempty"`
	Filename        *string  `thrift:"filename,4,optional" frugal:"4,optional,string" json:"filename,omitempty"`
	FileSize        *int64   `thrift:"file_size,5,optional" frugal:"5,optional,i64" json:"file_size,omitempty"`
	Width           *int32   `thrift:"width,6,optional" frugal:"6,optional,i32" json:"width,omitempty"`
	Height          *int32   `thrift:"height,7,optional" frugal:"7,optional,i32" json:"height,omitempty"`
	Url             *string  `thrift:"url,8,optional" frugal:"8,optional,string" json:"url,omitempty"`
	TranscodeUrls   []string `thrift:"transcode_urls,9,optional" frugal:"9,optional,list<string>" json:"transcode_urls,omitempty"`
	TranscodeStatus *string  `thrift:"transcode_status,10,optional" frugal:"10,optional,string" json:"transcode_status,omitempty"`
}

func NewGetVideoInfoResp() *GetVideoInfoResp {
	return &GetVideoInfoResp{}
}

func (p *GetVideoInfoResp) InitDefault() {
}

func (p *GetVideoInfoResp) GetCode() (v int32) {
	return p.Code
}

func (p *GetVideoInfoResp) GetMsg() (v string) {
	return p.Msg
}

var GetVideoInfoResp_FileHash_DEFAULT string

func (p *GetVideoInfoResp) GetFileHash() (v string) {
	if !p.IsSetFileHash() {
		return GetVideoInfoResp_FileHash_DEFAULT
	}
	return *p.FileHash
}

var GetVideoInfoResp_Filename_DEFAULT string

func (p *GetVideoInfoResp) GetFilename() (v string) {
	if !p.IsSetFilename() {
		return GetVideoInfoResp_Filename_DEFAULT
	}
	return *p.Filename
}

var GetVideoInfoResp_FileSize_DEFAULT int64

func (p *GetVideoInfoResp) GetFileSize() (v int64) {
	if !p.IsSetFileSize() {
		return GetVideoInfoResp_FileSize_DEFAULT
	}
	return *p.FileSize
}

var GetVideoInfoResp_Width_DEFAULT int32

func (p *GetVideoInfoResp) GetWidth() (v int32) {
	if !p.IsSetWidth() {
		return GetVideoInfoResp_Width_DEFAULT
	}
	return *p.Width
}

var GetVideoInfoResp_Height_DEFAULT int32

func (p *GetVideoInfoResp) GetHeight() (v int32) {
	if !p.IsSetHeight() {
		return GetVideoInfoResp_Height_DEFAULT
	}
	return *p.Height
}

var GetVideoInfoResp_Url_DEFAULT string

func (p *GetVideoInfoResp) GetUrl() (v string) {
	if !p.IsSetUrl() {
		return GetVideoInfoResp_Url_DEFAULT
	}
	return *p.Url
}

var GetVideoInfoResp_TranscodeUrls_DEFAULT []string

func (p *GetVideoInfoResp) GetTranscodeUrls() (v []string) {
	if !p.IsSetTranscodeUrls() {
		return GetVideoInfoResp_TranscodeUrls_DEFAULT
	}
	return p.TranscodeUrls
}

var GetVideoInfoResp_TranscodeStatus_DEFAULT string

func (p *GetVideoInfoResp) GetTranscodeStatus() (v string) {
	if !p.IsSetTranscodeStatus() {
		return GetVideoInfoResp_TranscodeStatus_DEFAULT
	}
	return *p.TranscodeStatus
}
func (p *GetVideoInfoResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetVideoInfoResp) SetMsg(val string) {
	p.Msg = val
}
func (p *GetVideoInfoResp) SetFileHash(val *string) {
	p.FileHash = val
}
func (p *GetVideoInfoResp) SetFilename(val *string) {
	p.Filename = val
}
func (p *GetVideoInfoResp) SetFileSize(val *int64) {
	p.FileSize = val
}
func (p *GetVideoInfoResp) SetWidth(val *int32) {
	p.Width = val
}
func (p *GetVideoInfoResp) SetHeight(val *int32) {
	p.Height = val
}
func (p *GetVideoInfoResp) SetUrl(val *string) {
	p.Url = val
}
func (p *GetVideoInfoResp) SetTranscodeUrls(val []string) {
	p.TranscodeUrls = val
}
func (p *GetVideoInfoResp) SetTranscodeStatus(val *string) {
	p.TranscodeStatus = val
}

func (p *GetVideoInfoResp) IsSetFileHash() bool {
	return p.FileHash != nil
}

func (p *GetVideoInfoResp) IsSetFilename() bool {
	return p.Filename != nil
}

func (p *GetVideoInfoResp) IsSetFileSize() bool {
	return p.FileSize != nil
}

func (p *GetVideoInfoResp) IsSetWidth() bool {
	return p.Width != nil
}

func (p *GetVideoInfoResp) IsSetHeight() bool {
	return p.Height != nil
}

func (p *GetVideoInfoResp) IsSetUrl() bool {
	return p.Url != nil
}

func (p *GetVideoInfoResp) IsSetTranscodeUrls() bool {
	return p.TranscodeUrls != nil
}

func (p *GetVideoInfoResp) IsSetTranscodeStatus() bool {
	return p.TranscodeStatus != nil
}

func (p *GetVideoInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoInfoResp(%+v)", *p)
}

var fieldIDToName_GetVideoInfoResp = map[int16]string{
	1:  "code",
	2:  "msg",
	3:  "file_hash",
	4:  "filename",
	5:  "file_size",
	6:  "width",
	7:  "height",
	8:  "url",
	9:  "transcode_urls",
	10: "transcode_status",
}

type DeleteVideoReq struct {
	FileHash string `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	UserId   string `thrift:"user_id,2,required" frugal:"2,required,string" json:"user_id"`
}

func NewDeleteVideoReq() *DeleteVideoReq {
	return &DeleteVideoReq{}
}

func (p *DeleteVideoReq) InitDefault() {
}

func (p *DeleteVideoReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *DeleteVideoReq) GetUserId() (v string) {
	return p.UserId
}
func (p *DeleteVideoReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *DeleteVideoReq) SetUserId(val string) {
	p.UserId = val
}

func (p *DeleteVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteVideoReq(%+v)", *p)
}

var fieldIDToName_DeleteVideoReq = map[int16]string{
	1: "file_hash",
	2: "user_id",
}

type DeleteVideoResp struct {
	Code int32  `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg  string `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
}

func NewDeleteVideoResp() *DeleteVideoResp {
	return &DeleteVideoResp{}
}

func (p *DeleteVideoResp) InitDefault() {
}

func (p *DeleteVideoResp) GetCode() (v int32) {
	return p.Code
}

func (p *DeleteVideoResp) GetMsg() (v string) {
	return p.Msg
}
func (p *DeleteVideoResp) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteVideoResp) SetMsg(val string) {
	p.Msg = val
}

func (p *DeleteVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteVideoResp(%+v)", *p)
}

var fieldIDToName_DeleteVideoResp = map[int16]string{
	1: "code",
	2: "msg",
}

type TranscodeReq struct {
	FileHash    string   `thrift:"file_hash,1,required" frugal:"1,required,string" json:"file_hash"`
	UserId      string   `thrift:"user_id,2,required" frugal:"2,required,string" json:"user_id"`
	Resolutions []string `thrift:"resolutions,3,required" frugal:"3,required,list<string>" json:"resolutions"`
	RequestId   *string  `thrift:"request_id,4,optional" frugal:"4,optional,string" json:"request_id,omitempty"`
}

func NewTranscodeReq() *TranscodeReq {
	return &TranscodeReq{}
}

func (p *TranscodeReq) InitDefault() {
}

func (p *TranscodeReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *TranscodeReq) GetUserId() (v string) {
	return p.UserId
}

func (p *TranscodeReq) GetResolutions() (v []string) {
	return p.Resolutions
}

var TranscodeReq_RequestId_DEFAULT string

func (p *TranscodeReq) GetRequestId() (v string) {
	if !p.IsSetRequestId() {
		return TranscodeReq_RequestId_DEFAULT
	}
	return *p.RequestId
}
func (p *TranscodeReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *TranscodeReq) SetUserId(val string) {
	p.UserId = val
}
func (p *TranscodeReq) SetResolutions(val []string) {
	p.Resolutions = val
}
func (p *TranscodeReq) SetRequestId(val *string) {
	p.RequestId = val
}

func (p *TranscodeReq) IsSetRequestId() bool {
	return p.RequestId != nil
}

func (p *TranscodeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeReq(%+v)", *p)
}

var fieldIDToName_TranscodeReq = map[int16]string{
	1: "file_hash",
	2: "user_id",
	3: "resolutions",
	4: "request_id",
}

type TranscodeResp struct {
	Code   int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg    string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	TaskId *string `thrift:"task_id,3,optional" frugal:"3,optional,string" json:"task_id,omitempty"`
}

func NewTranscodeResp() *TranscodeResp {
	return &TranscodeResp{}
}

func (p *TranscodeResp) InitDefault() {
}

func (p *TranscodeResp) GetCode() (v int32) {
	return p.Code
}

func (p *TranscodeResp) GetMsg() (v string) {
	return p.Msg
}

var TranscodeResp_TaskId_DEFAULT string

func (p *TranscodeResp) GetTaskId() (v string) {
	if !p.IsSetTaskId() {
		return TranscodeResp_TaskId_DEFAULT
	}
	return *p.TaskId
}
func (p *TranscodeResp) SetCode(val int32) {
	p.Code = val
}
func (p *TranscodeResp) SetMsg(val string) {
	p.Msg = val
}
func (p *TranscodeResp) SetTaskId(val *string) {
	p.TaskId = val
}

func (p *TranscodeResp) IsSetTaskId() bool {
	return p.TaskId != nil
}

func (p *TranscodeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TranscodeResp(%+v)", *p)
}

var fieldIDToName_TranscodeResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "task_id",
}

type GetTranscodeStatusReq struct {
	TaskId string `thrift:"task_id,1,required" frugal:"1,required,string" json:"task_id"`
}

func NewGetTranscodeStatusReq() *GetTranscodeStatusReq {
	return &GetTranscodeStatusReq{}
}

func (p *GetTranscodeStatusReq) InitDefault() {
}

func (p *GetTranscodeStatusReq) GetTaskId() (v string) {
	return p.TaskId
}
func (p *GetTranscodeStatusReq) SetTaskId(val string) {
	p.TaskId = val
}

func (p *GetTranscodeStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTranscodeStatusReq(%+v)", *p)
}

var fieldIDToName_GetTranscodeStatusReq = map[int16]string{
	1: "task_id",
}

type GetTranscodeStatusResp struct {
	Code          int32    `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg           string   `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	Status        *string  `thrift:"status,3,optional" frugal:"3,optional,string" json:"status,omitempty"`
	Progress      *float64 `thrift:"progress,4,optional" frugal:"4,optional,double" json:"progress,omitempty"`
	CompletedUrls []string `thrift:"completed_urls,5,optional" frugal:"5,optional,list<string>" json:"completed_urls,omitempty"`
}

func NewGetTranscodeStatusResp() *GetTranscodeStatusResp {
	return &GetTranscodeStatusResp{}
}

func (p *GetTranscodeStatusResp) InitDefault() {
}

func (p *GetTranscodeStatusResp) GetCode() (v int32) {
	return p.Code
}

func (p *GetTranscodeStatusResp) GetMsg() (v string) {
	return p.Msg
}

var GetTranscodeStatusResp_Status_DEFAULT string

func (p *GetTranscodeStatusResp) GetStatus() (v string) {
	if !p.IsSetStatus() {
		return GetTranscodeStatusResp_Status_DEFAULT
	}
	return *p.Status
}

var GetTranscodeStatusResp_Progress_DEFAULT float64

func (p *GetTranscodeStatusResp) GetProgress() (v float64) {
	if !p.IsSetProgress() {
		return GetTranscodeStatusResp_Progress_DEFAULT
	}
	return *p.Progress
}

var GetTranscodeStatusResp_CompletedUrls_DEFAULT []string

func (p *GetTranscodeStatusResp) GetCompletedUrls() (v []string) {
	if !p.IsSetCompletedUrls() {
		return GetTranscodeStatusResp_CompletedUrls_DEFAULT
	}
	return p.CompletedUrls
}
func (p *GetTranscodeStatusResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetTranscodeStatusResp) SetMsg(val string) {
	p.Msg = val
}
func (p *GetTranscodeStatusResp) SetStatus(val *string) {
	p.Status = val
}
func (p *GetTranscodeStatusResp) SetProgress(val *float64) {
	p.Progress = val
}
func (p *GetTranscodeStatusResp) SetCompletedUrls(val []string) {
	p.CompletedUrls = val
}

func (p *GetTranscodeStatusResp) IsSetStatus() bool {
	return p.Status != nil
}

func (p *GetTranscodeStatusResp) IsSetProgress() bool {
	return p.Progress != nil
}

func (p *GetTranscodeStatusResp) IsSetCompletedUrls() bool {
	return p.CompletedUrls != nil
}

func (p *GetTranscodeStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTranscodeStatusResp(%+v)", *p)
}

var fieldIDToName_GetTranscodeStatusResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "status",
	4: "progress",
	5: "completed_urls",
}

type VideoManagerService interface {
	InitUpload(ctx context.Context, req *InitUploadReq) (r *InitUploadResp, err error)

	FinalizeUpload(ctx context.Context, req *FinalizeUploadReq) (r *FinalizeUploadResp, err error)

	QueryUploadProgress(ctx context.Context, req *QueryUploadProgressReq) (r *QueryUploadProgressResp, err error)

	AbortUpload(ctx context.Context, req *AbortUploadReq) (r *AbortUploadResp, err error)

	GetVideoInfo(ctx context.Context, req *GetVideoInfoReq) (r *GetVideoInfoResp, err error)

	DeleteVideo(ctx context.Context, req *DeleteVideoReq) (r *DeleteVideoResp, err error)

	Transcode(ctx context.Context, req *TranscodeReq) (r *TranscodeResp, err error)

	GetTranscodeStatus(ctx context.Context, req *GetTranscodeStatusReq) (r *GetTranscodeStatusResp, err error)
}

type VideoManagerServiceInitUploadArgs struct {
	Req *InitUploadReq `thrift:"req,1" frugal:"1,default,InitUploadReq" json:"req"`
}

func NewVideoManagerServiceInitUploadArgs() *VideoManagerServiceInitUploadArgs {
	return &VideoManagerServiceInitUploadArgs{}
}

func (p *VideoManagerServiceInitUploadArgs) InitDefault() {
}

var VideoManagerServiceInitUploadArgs_Req_DEFAULT *InitUploadReq

func (p *VideoManagerServiceInitUploadArgs) GetReq() (v *InitUploadReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceInitUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceInitUploadArgs) SetReq(val *InitUploadReq) {
	p.Req = val
}

func (p *VideoManagerServiceInitUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceInitUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceInitUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceInitUploadArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceInitUploadResult struct {
	Success *InitUploadResp `thrift:"success,0,optional" frugal:"0,optional,InitUploadResp" json:"success,omitempty"`
}

func NewVideoManagerServiceInitUploadResult() *VideoManagerServiceInitUploadResult {
	return &VideoManagerServiceInitUploadResult{}
}

func (p *VideoManagerServiceInitUploadResult) InitDefault() {
}

var VideoManagerServiceInitUploadResult_Success_DEFAULT *InitUploadResp

func (p *VideoManagerServiceInitUploadResult) GetSuccess() (v *InitUploadResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceInitUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceInitUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*InitUploadResp)
}

func (p *VideoManagerServiceInitUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceInitUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceInitUploadResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceInitUploadResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceFinalizeUploadArgs struct {
	Req *FinalizeUploadReq `thrift:"req,1" frugal:"1,default,FinalizeUploadReq" json:"req"`
}

func NewVideoManagerServiceFinalizeUploadArgs() *VideoManagerServiceFinalizeUploadArgs {
	return &VideoManagerServiceFinalizeUploadArgs{}
}

func (p *VideoManagerServiceFinalizeUploadArgs) InitDefault() {
}

var VideoManagerServiceFinalizeUploadArgs_Req_DEFAULT *FinalizeUploadReq

func (p *VideoManagerServiceFinalizeUploadArgs) GetReq() (v *FinalizeUploadReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceFinalizeUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceFinalizeUploadArgs) SetReq(val *FinalizeUploadReq) {
	p.Req = val
}

func (p *VideoManagerServiceFinalizeUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceFinalizeUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceFinalizeUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceFinalizeUploadArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceFinalizeUploadResult struct {
	Success *FinalizeUploadResp `thrift:"success,0,optional" frugal:"0,optional,FinalizeUploadResp" json:"success,omitempty"`
}

func NewVideoManagerServiceFinalizeUploadResult() *VideoManagerServiceFinalizeUploadResult {
	return &VideoManagerServiceFinalizeUploadResult{}
}

func (p *VideoManagerServiceFinalizeUploadResult) InitDefault() {
}

var VideoManagerServiceFinalizeUploadResult_Success_DEFAULT *FinalizeUploadResp

func (p *VideoManagerServiceFinalizeUploadResult) GetSuccess() (v *FinalizeUploadResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceFinalizeUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceFinalizeUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*FinalizeUploadResp)
}

func (p *VideoManagerServiceFinalizeUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceFinalizeUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceFinalizeUploadResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceFinalizeUploadResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceQueryUploadProgressArgs struct {
	Req *QueryUploadProgressReq `thrift:"req,1" frugal:"1,default,QueryUploadProgressReq" json:"req"`
}

func NewVideoManagerServiceQueryUploadProgressArgs() *VideoManagerServiceQueryUploadProgressArgs {
	return &VideoManagerServiceQueryUploadProgressArgs{}
}

func (p *VideoManagerServiceQueryUploadProgressArgs) InitDefault() {
}

var VideoManagerServiceQueryUploadProgressArgs_Req_DEFAULT *QueryUploadProgressReq

func (p *VideoManagerServiceQueryUploadProgressArgs) GetReq() (v *QueryUploadProgressReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceQueryUploadProgressArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceQueryUploadProgressArgs) SetReq(val *QueryUploadProgressReq) {
	p.Req = val
}

func (p *VideoManagerServiceQueryUploadProgressArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceQueryUploadProgressArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceQueryUploadProgressArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceQueryUploadProgressArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceQueryUploadProgressResult struct {
	Success *QueryUploadProgressResp `thrift:"success,0,optional" frugal:"0,optional,QueryUploadProgressResp" json:"success,omitempty"`
}

func NewVideoManagerServiceQueryUploadProgressResult() *VideoManagerServiceQueryUploadProgressResult {
	return &VideoManagerServiceQueryUploadProgressResult{}
}

func (p *VideoManagerServiceQueryUploadProgressResult) InitDefault() {
}

var VideoManagerServiceQueryUploadProgressResult_Success_DEFAULT *QueryUploadProgressResp

func (p *VideoManagerServiceQueryUploadProgressResult) GetSuccess() (v *QueryUploadProgressResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceQueryUploadProgressResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceQueryUploadProgressResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryUploadProgressResp)
}

func (p *VideoManagerServiceQueryUploadProgressResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceQueryUploadProgressResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceQueryUploadProgressResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceQueryUploadProgressResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceAbortUploadArgs struct {
	Req *AbortUploadReq `thrift:"req,1" frugal:"1,default,AbortUploadReq" json:"req"`
}

func NewVideoManagerServiceAbortUploadArgs() *VideoManagerServiceAbortUploadArgs {
	return &VideoManagerServiceAbortUploadArgs{}
}

func (p *VideoManagerServiceAbortUploadArgs) InitDefault() {
}

var VideoManagerServiceAbortUploadArgs_Req_DEFAULT *AbortUploadReq

func (p *VideoManagerServiceAbortUploadArgs) GetReq() (v *AbortUploadReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceAbortUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceAbortUploadArgs) SetReq(val *AbortUploadReq) {
	p.Req = val
}

func (p *VideoManagerServiceAbortUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceAbortUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceAbortUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceAbortUploadArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceAbortUploadResult struct {
	Success *AbortUploadResp `thrift:"success,0,optional" frugal:"0,optional,AbortUploadResp" json:"success,omitempty"`
}

func NewVideoManagerServiceAbortUploadResult() *VideoManagerServiceAbortUploadResult {
	return &VideoManagerServiceAbortUploadResult{}
}

func (p *VideoManagerServiceAbortUploadResult) InitDefault() {
}

var VideoManagerServiceAbortUploadResult_Success_DEFAULT *AbortUploadResp

func (p *VideoManagerServiceAbortUploadResult) GetSuccess() (v *AbortUploadResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceAbortUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceAbortUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*AbortUploadResp)
}

func (p *VideoManagerServiceAbortUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceAbortUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceAbortUploadResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceAbortUploadResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceGetVideoInfoArgs struct {
	Req *GetVideoInfoReq `thrift:"req,1" frugal:"1,default,GetVideoInfoReq" json:"req"`
}

func NewVideoManagerServiceGetVideoInfoArgs() *VideoManagerServiceGetVideoInfoArgs {
	return &VideoManagerServiceGetVideoInfoArgs{}
}

func (p *VideoManagerServiceGetVideoInfoArgs) InitDefault() {
}

var VideoManagerServiceGetVideoInfoArgs_Req_DEFAULT *GetVideoInfoReq

func (p *VideoManagerServiceGetVideoInfoArgs) GetReq() (v *GetVideoInfoReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceGetVideoInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceGetVideoInfoArgs) SetReq(val *GetVideoInfoReq) {
	p.Req = val
}

func (p *VideoManagerServiceGetVideoInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceGetVideoInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceGetVideoInfoArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceGetVideoInfoArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceGetVideoInfoResult struct {
	Success *GetVideoInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetVideoInfoResp" json:"success,omitempty"`
}

func NewVideoManagerServiceGetVideoInfoResult() *VideoManagerServiceGetVideoInfoResult {
	return &VideoManagerServiceGetVideoInfoResult{}
}

func (p *VideoManagerServiceGetVideoInfoResult) InitDefault() {
}

var VideoManagerServiceGetVideoInfoResult_Success_DEFAULT *GetVideoInfoResp

func (p *VideoManagerServiceGetVideoInfoResult) GetSuccess() (v *GetVideoInfoResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceGetVideoInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceGetVideoInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetVideoInfoResp)
}

func (p *VideoManagerServiceGetVideoInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceGetVideoInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceGetVideoInfoResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceGetVideoInfoResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceDeleteVideoArgs struct {
	Req *DeleteVideoReq `thrift:"req,1" frugal:"1,default,DeleteVideoReq" json:"req"`
}

func NewVideoManagerServiceDeleteVideoArgs() *VideoManagerServiceDeleteVideoArgs {
	return &VideoManagerServiceDeleteVideoArgs{}
}

func (p *VideoManagerServiceDeleteVideoArgs) InitDefault() {
}

var VideoManagerServiceDeleteVideoArgs_Req_DEFAULT *DeleteVideoReq

func (p *VideoManagerServiceDeleteVideoArgs) GetReq() (v *DeleteVideoReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceDeleteVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceDeleteVideoArgs) SetReq(val *DeleteVideoReq) {
	p.Req = val
}

func (p *VideoManagerServiceDeleteVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceDeleteVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceDeleteVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceDeleteVideoArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceDeleteVideoResult struct {
	Success *DeleteVideoResp `thrift:"success,0,optional" frugal:"0,optional,DeleteVideoResp" json:"success,omitempty"`
}

func NewVideoManagerServiceDeleteVideoResult() *VideoManagerServiceDeleteVideoResult {
	return &VideoManagerServiceDeleteVideoResult{}
}

func (p *VideoManagerServiceDeleteVideoResult) InitDefault() {
}

var VideoManagerServiceDeleteVideoResult_Success_DEFAULT *DeleteVideoResp

func (p *VideoManagerServiceDeleteVideoResult) GetSuccess() (v *DeleteVideoResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceDeleteVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceDeleteVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteVideoResp)
}

func (p *VideoManagerServiceDeleteVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceDeleteVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceDeleteVideoResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceDeleteVideoResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceTranscodeArgs struct {
	Req *TranscodeReq `thrift:"req,1" frugal:"1,default,TranscodeReq" json:"req"`
}

func NewVideoManagerServiceTranscodeArgs() *VideoManagerServiceTranscodeArgs {
	return &VideoManagerServiceTranscodeArgs{}
}

func (p *VideoManagerServiceTranscodeArgs) InitDefault() {
}

var VideoManagerServiceTranscodeArgs_Req_DEFAULT *TranscodeReq

func (p *VideoManagerServiceTranscodeArgs) GetReq() (v *TranscodeReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceTranscodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceTranscodeArgs) SetReq(val *TranscodeReq) {
	p.Req = val
}

func (p *VideoManagerServiceTranscodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceTranscodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceTranscodeArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceTranscodeArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceTranscodeResult struct {
	Success *TranscodeResp `thrift:"success,0,optional" frugal:"0,optional,TranscodeResp" json:"success,omitempty"`
}

func NewVideoManagerServiceTranscodeResult() *VideoManagerServiceTranscodeResult {
	return &VideoManagerServiceTranscodeResult{}
}

func (p *VideoManagerServiceTranscodeResult) InitDefault() {
}

var VideoManagerServiceTranscodeResult_Success_DEFAULT *TranscodeResp

func (p *VideoManagerServiceTranscodeResult) GetSuccess() (v *TranscodeResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceTranscodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceTranscodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*TranscodeResp)
}

func (p *VideoManagerServiceTranscodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceTranscodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceTranscodeResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceTranscodeResult = map[int16]string{
	0: "success",
}

type VideoManagerServiceGetTranscodeStatusArgs struct {
	Req *GetTranscodeStatusReq `thrift:"req,1" frugal:"1,default,GetTranscodeStatusReq" json:"req"`
}

func NewVideoManagerServiceGetTranscodeStatusArgs() *VideoManagerServiceGetTranscodeStatusArgs {
	return &VideoManagerServiceGetTranscodeStatusArgs{}
}

func (p *VideoManagerServiceGetTranscodeStatusArgs) InitDefault() {
}

var VideoManagerServiceGetTranscodeStatusArgs_Req_DEFAULT *GetTranscodeStatusReq

func (p *VideoManagerServiceGetTranscodeStatusArgs) GetReq() (v *GetTranscodeStatusReq) {
	if !p.IsSetReq() {
		return VideoManagerServiceGetTranscodeStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoManagerServiceGetTranscodeStatusArgs) SetReq(val *GetTranscodeStatusReq) {
	p.Req = val
}

func (p *VideoManagerServiceGetTranscodeStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoManagerServiceGetTranscodeStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceGetTranscodeStatusArgs(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceGetTranscodeStatusArgs = map[int16]string{
	1: "req",
}

type VideoManagerServiceGetTranscodeStatusResult struct {
	Success *GetTranscodeStatusResp `thrift:"success,0,optional" frugal:"0,optional,GetTranscodeStatusResp" json:"success,omitempty"`
}

func NewVideoManagerServiceGetTranscodeStatusResult() *VideoManagerServiceGetTranscodeStatusResult {
	return &VideoManagerServiceGetTranscodeStatusResult{}
}

func (p *VideoManagerServiceGetTranscodeStatusResult) InitDefault() {
}

var VideoManagerServiceGetTranscodeStatusResult_Success_DEFAULT *GetTranscodeStatusResp

func (p *VideoManagerServiceGetTranscodeStatusResult) GetSuccess() (v *GetTranscodeStatusResp) {
	if !p.IsSetSuccess() {
		return VideoManagerServiceGetTranscodeStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoManagerServiceGetTranscodeStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTranscodeStatusResp)
}

func (p *VideoManagerServiceGetTranscodeStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoManagerServiceGetTranscodeStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoManagerServiceGetTranscodeStatusResult(%+v)", *p)
}

var fieldIDToName_VideoManagerServiceGetTranscodeStatusResult = map[int16]string{
	0: "success",
}
