// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package video

import (
	"context"
	"fmt"
)

type InitUploadReq struct {
	FileHash string `thrift:"file_hash,1" frugal:"1,default,string" json:"file_hash"`
	Filename string `thrift:"filename,2" frugal:"2,default,string" json:"filename"`
}

func NewInitUploadReq() *InitUploadReq {
	return &InitUploadReq{}
}

func (p *InitUploadReq) InitDefault() {
}

func (p *InitUploadReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *InitUploadReq) GetFilename() (v string) {
	return p.Filename
}
func (p *InitUploadReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *InitUploadReq) SetFilename(val string) {
	p.Filename = val
}

func (p *InitUploadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadReq(%+v)", *p)
}

var fieldIDToName_InitUploadReq = map[int16]string{
	1: "file_hash",
	2: "filename",
}

type InitUploadResp struct {
	Code           int32    `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg            string   `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
	Status         string   `thrift:"status,3" frugal:"3,default,string" json:"status"`
	FinishedChunks []string `thrift:"finished_chunks,4" frugal:"4,default,list<string>" json:"finished_chunks"`
	Url            string   `thrift:"url,5" frugal:"5,default,string" json:"url"`
}

func NewInitUploadResp() *InitUploadResp {
	return &InitUploadResp{}
}

func (p *InitUploadResp) InitDefault() {
}

func (p *InitUploadResp) GetCode() (v int32) {
	return p.Code
}

func (p *InitUploadResp) GetMsg() (v string) {
	return p.Msg
}

func (p *InitUploadResp) GetStatus() (v string) {
	return p.Status
}

func (p *InitUploadResp) GetFinishedChunks() (v []string) {
	return p.FinishedChunks
}

func (p *InitUploadResp) GetUrl() (v string) {
	return p.Url
}
func (p *InitUploadResp) SetCode(val int32) {
	p.Code = val
}
func (p *InitUploadResp) SetMsg(val string) {
	p.Msg = val
}
func (p *InitUploadResp) SetStatus(val string) {
	p.Status = val
}
func (p *InitUploadResp) SetFinishedChunks(val []string) {
	p.FinishedChunks = val
}
func (p *InitUploadResp) SetUrl(val string) {
	p.Url = val
}

func (p *InitUploadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InitUploadResp(%+v)", *p)
}

var fieldIDToName_InitUploadResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "status",
	4: "finished_chunks",
	5: "url",
}

type UploadChunkReq struct {
	FileHash string `thrift:"file_hash,1" frugal:"1,default,string" json:"file_hash"`
	Index    string `thrift:"index,2" frugal:"2,default,string" json:"index"`
	Data     []byte `thrift:"data,3" frugal:"3,default,binary" json:"data"`
}

func NewUploadChunkReq() *UploadChunkReq {
	return &UploadChunkReq{}
}

func (p *UploadChunkReq) InitDefault() {
}

func (p *UploadChunkReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *UploadChunkReq) GetIndex() (v string) {
	return p.Index
}

func (p *UploadChunkReq) GetData() (v []byte) {
	return p.Data
}
func (p *UploadChunkReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *UploadChunkReq) SetIndex(val string) {
	p.Index = val
}
func (p *UploadChunkReq) SetData(val []byte) {
	p.Data = val
}

func (p *UploadChunkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadChunkReq(%+v)", *p)
}

var fieldIDToName_UploadChunkReq = map[int16]string{
	1: "file_hash",
	2: "index",
	3: "data",
}

type UploadChunkResp struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewUploadChunkResp() *UploadChunkResp {
	return &UploadChunkResp{}
}

func (p *UploadChunkResp) InitDefault() {
}

func (p *UploadChunkResp) GetCode() (v int32) {
	return p.Code
}

func (p *UploadChunkResp) GetMsg() (v string) {
	return p.Msg
}
func (p *UploadChunkResp) SetCode(val int32) {
	p.Code = val
}
func (p *UploadChunkResp) SetMsg(val string) {
	p.Msg = val
}

func (p *UploadChunkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadChunkResp(%+v)", *p)
}

var fieldIDToName_UploadChunkResp = map[int16]string{
	1: "code",
	2: "msg",
}

type MergeFileReq struct {
	FileHash    string `thrift:"file_hash,1" frugal:"1,default,string" json:"file_hash"`
	Filename    string `thrift:"filename,2" frugal:"2,default,string" json:"filename"`
	TotalChunks int32  `thrift:"total_chunks,3" frugal:"3,default,i32" json:"total_chunks"`
}

func NewMergeFileReq() *MergeFileReq {
	return &MergeFileReq{}
}

func (p *MergeFileReq) InitDefault() {
}

func (p *MergeFileReq) GetFileHash() (v string) {
	return p.FileHash
}

func (p *MergeFileReq) GetFilename() (v string) {
	return p.Filename
}

func (p *MergeFileReq) GetTotalChunks() (v int32) {
	return p.TotalChunks
}
func (p *MergeFileReq) SetFileHash(val string) {
	p.FileHash = val
}
func (p *MergeFileReq) SetFilename(val string) {
	p.Filename = val
}
func (p *MergeFileReq) SetTotalChunks(val int32) {
	p.TotalChunks = val
}

func (p *MergeFileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MergeFileReq(%+v)", *p)
}

var fieldIDToName_MergeFileReq = map[int16]string{
	1: "file_hash",
	2: "filename",
	3: "total_chunks",
}

type MergeFileResp struct {
	Code int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Msg  string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
	Url  string `thrift:"url,3" frugal:"3,default,string" json:"url"`
}

func NewMergeFileResp() *MergeFileResp {
	return &MergeFileResp{}
}

func (p *MergeFileResp) InitDefault() {
}

func (p *MergeFileResp) GetCode() (v int32) {
	return p.Code
}

func (p *MergeFileResp) GetMsg() (v string) {
	return p.Msg
}

func (p *MergeFileResp) GetUrl() (v string) {
	return p.Url
}
func (p *MergeFileResp) SetCode(val int32) {
	p.Code = val
}
func (p *MergeFileResp) SetMsg(val string) {
	p.Msg = val
}
func (p *MergeFileResp) SetUrl(val string) {
	p.Url = val
}

func (p *MergeFileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MergeFileResp(%+v)", *p)
}

var fieldIDToName_MergeFileResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "url",
}

type VideoService interface {
	InitUpload(ctx context.Context, req *InitUploadReq) (r *InitUploadResp, err error)

	UploadChunk(ctx context.Context, req *UploadChunkReq) (r *UploadChunkResp, err error)

	MergeFile(ctx context.Context, req *MergeFileReq) (r *MergeFileResp, err error)
}

type VideoServiceInitUploadArgs struct {
	Req *InitUploadReq `thrift:"req,1" frugal:"1,default,InitUploadReq" json:"req"`
}

func NewVideoServiceInitUploadArgs() *VideoServiceInitUploadArgs {
	return &VideoServiceInitUploadArgs{}
}

func (p *VideoServiceInitUploadArgs) InitDefault() {
}

var VideoServiceInitUploadArgs_Req_DEFAULT *InitUploadReq

func (p *VideoServiceInitUploadArgs) GetReq() (v *InitUploadReq) {
	if !p.IsSetReq() {
		return VideoServiceInitUploadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceInitUploadArgs) SetReq(val *InitUploadReq) {
	p.Req = val
}

func (p *VideoServiceInitUploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceInitUploadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceInitUploadArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceInitUploadArgs = map[int16]string{
	1: "req",
}

type VideoServiceInitUploadResult struct {
	Success *InitUploadResp `thrift:"success,0,optional" frugal:"0,optional,InitUploadResp" json:"success,omitempty"`
}

func NewVideoServiceInitUploadResult() *VideoServiceInitUploadResult {
	return &VideoServiceInitUploadResult{}
}

func (p *VideoServiceInitUploadResult) InitDefault() {
}

var VideoServiceInitUploadResult_Success_DEFAULT *InitUploadResp

func (p *VideoServiceInitUploadResult) GetSuccess() (v *InitUploadResp) {
	if !p.IsSetSuccess() {
		return VideoServiceInitUploadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceInitUploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*InitUploadResp)
}

func (p *VideoServiceInitUploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceInitUploadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceInitUploadResult(%+v)", *p)
}

var fieldIDToName_VideoServiceInitUploadResult = map[int16]string{
	0: "success",
}

type VideoServiceUploadChunkArgs struct {
	Req *UploadChunkReq `thrift:"req,1" frugal:"1,default,UploadChunkReq" json:"req"`
}

func NewVideoServiceUploadChunkArgs() *VideoServiceUploadChunkArgs {
	return &VideoServiceUploadChunkArgs{}
}

func (p *VideoServiceUploadChunkArgs) InitDefault() {
}

var VideoServiceUploadChunkArgs_Req_DEFAULT *UploadChunkReq

func (p *VideoServiceUploadChunkArgs) GetReq() (v *UploadChunkReq) {
	if !p.IsSetReq() {
		return VideoServiceUploadChunkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceUploadChunkArgs) SetReq(val *UploadChunkReq) {
	p.Req = val
}

func (p *VideoServiceUploadChunkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceUploadChunkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceUploadChunkArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceUploadChunkArgs = map[int16]string{
	1: "req",
}

type VideoServiceUploadChunkResult struct {
	Success *UploadChunkResp `thrift:"success,0,optional" frugal:"0,optional,UploadChunkResp" json:"success,omitempty"`
}

func NewVideoServiceUploadChunkResult() *VideoServiceUploadChunkResult {
	return &VideoServiceUploadChunkResult{}
}

func (p *VideoServiceUploadChunkResult) InitDefault() {
}

var VideoServiceUploadChunkResult_Success_DEFAULT *UploadChunkResp

func (p *VideoServiceUploadChunkResult) GetSuccess() (v *UploadChunkResp) {
	if !p.IsSetSuccess() {
		return VideoServiceUploadChunkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceUploadChunkResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadChunkResp)
}

func (p *VideoServiceUploadChunkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceUploadChunkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceUploadChunkResult(%+v)", *p)
}

var fieldIDToName_VideoServiceUploadChunkResult = map[int16]string{
	0: "success",
}

type VideoServiceMergeFileArgs struct {
	Req *MergeFileReq `thrift:"req,1" frugal:"1,default,MergeFileReq" json:"req"`
}

func NewVideoServiceMergeFileArgs() *VideoServiceMergeFileArgs {
	return &VideoServiceMergeFileArgs{}
}

func (p *VideoServiceMergeFileArgs) InitDefault() {
}

var VideoServiceMergeFileArgs_Req_DEFAULT *MergeFileReq

func (p *VideoServiceMergeFileArgs) GetReq() (v *MergeFileReq) {
	if !p.IsSetReq() {
		return VideoServiceMergeFileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoServiceMergeFileArgs) SetReq(val *MergeFileReq) {
	p.Req = val
}

func (p *VideoServiceMergeFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoServiceMergeFileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceMergeFileArgs(%+v)", *p)
}

var fieldIDToName_VideoServiceMergeFileArgs = map[int16]string{
	1: "req",
}

type VideoServiceMergeFileResult struct {
	Success *MergeFileResp `thrift:"success,0,optional" frugal:"0,optional,MergeFileResp" json:"success,omitempty"`
}

func NewVideoServiceMergeFileResult() *VideoServiceMergeFileResult {
	return &VideoServiceMergeFileResult{}
}

func (p *VideoServiceMergeFileResult) InitDefault() {
}

var VideoServiceMergeFileResult_Success_DEFAULT *MergeFileResp

func (p *VideoServiceMergeFileResult) GetSuccess() (v *MergeFileResp) {
	if !p.IsSetSuccess() {
		return VideoServiceMergeFileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoServiceMergeFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*MergeFileResp)
}

func (p *VideoServiceMergeFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoServiceMergeFileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoServiceMergeFileResult(%+v)", *p)
}

var fieldIDToName_VideoServiceMergeFileResult = map[int16]string{
	0: "success",
}
