// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videomanagerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videomanager "video-platform-microservice/gateway/kitex_gen/videomanager"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	InitUpload(ctx context.Context, req *videomanager.InitUploadReq, callOptions ...callopt.Option) (r *videomanager.InitUploadResp, err error)
	FinalizeUpload(ctx context.Context, req *videomanager.FinalizeUploadReq, callOptions ...callopt.Option) (r *videomanager.FinalizeUploadResp, err error)
	QueryUploadProgress(ctx context.Context, req *videomanager.QueryUploadProgressReq, callOptions ...callopt.Option) (r *videomanager.QueryUploadProgressResp, err error)
	AbortUpload(ctx context.Context, req *videomanager.AbortUploadReq, callOptions ...callopt.Option) (r *videomanager.AbortUploadResp, err error)
	GetVideoInfo(ctx context.Context, req *videomanager.GetVideoInfoReq, callOptions ...callopt.Option) (r *videomanager.GetVideoInfoResp, err error)
	DeleteVideo(ctx context.Context, req *videomanager.DeleteVideoReq, callOptions ...callopt.Option) (r *videomanager.DeleteVideoResp, err error)
	Transcode(ctx context.Context, req *videomanager.TranscodeReq, callOptions ...callopt.Option) (r *videomanager.TranscodeResp, err error)
	GetTranscodeStatus(ctx context.Context, req *videomanager.GetTranscodeStatusReq, callOptions ...callopt.Option) (r *videomanager.GetTranscodeStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoManagerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoManagerServiceClient struct {
	*kClient
}

func (p *kVideoManagerServiceClient) InitUpload(ctx context.Context, req *videomanager.InitUploadReq, callOptions ...callopt.Option) (r *videomanager.InitUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitUpload(ctx, req)
}

func (p *kVideoManagerServiceClient) FinalizeUpload(ctx context.Context, req *videomanager.FinalizeUploadReq, callOptions ...callopt.Option) (r *videomanager.FinalizeUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FinalizeUpload(ctx, req)
}

func (p *kVideoManagerServiceClient) QueryUploadProgress(ctx context.Context, req *videomanager.QueryUploadProgressReq, callOptions ...callopt.Option) (r *videomanager.QueryUploadProgressResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUploadProgress(ctx, req)
}

func (p *kVideoManagerServiceClient) AbortUpload(ctx context.Context, req *videomanager.AbortUploadReq, callOptions ...callopt.Option) (r *videomanager.AbortUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AbortUpload(ctx, req)
}

func (p *kVideoManagerServiceClient) GetVideoInfo(ctx context.Context, req *videomanager.GetVideoInfoReq, callOptions ...callopt.Option) (r *videomanager.GetVideoInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoInfo(ctx, req)
}

func (p *kVideoManagerServiceClient) DeleteVideo(ctx context.Context, req *videomanager.DeleteVideoReq, callOptions ...callopt.Option) (r *videomanager.DeleteVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteVideo(ctx, req)
}

func (p *kVideoManagerServiceClient) Transcode(ctx context.Context, req *videomanager.TranscodeReq, callOptions ...callopt.Option) (r *videomanager.TranscodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Transcode(ctx, req)
}

func (p *kVideoManagerServiceClient) GetTranscodeStatus(ctx context.Context, req *videomanager.GetTranscodeStatusReq, callOptions ...callopt.Option) (r *videomanager.GetTranscodeStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTranscodeStatus(ctx, req)
}
