// Code generated by Kitex v0.16.1. DO NOT EDIT.

package videomanagerservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	videomanager "video-platform-microservice/gateway/kitex_gen/videomanager"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"InitUpload": kitex.NewMethodInfo(
		initUploadHandler,
		newVideoManagerServiceInitUploadArgs,
		newVideoManagerServiceInitUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FinalizeUpload": kitex.NewMethodInfo(
		finalizeUploadHandler,
		newVideoManagerServiceFinalizeUploadArgs,
		newVideoManagerServiceFinalizeUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUploadProgress": kitex.NewMethodInfo(
		queryUploadProgressHandler,
		newVideoManagerServiceQueryUploadProgressArgs,
		newVideoManagerServiceQueryUploadProgressResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AbortUpload": kitex.NewMethodInfo(
		abortUploadHandler,
		newVideoManagerServiceAbortUploadArgs,
		newVideoManagerServiceAbortUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoInfo": kitex.NewMethodInfo(
		getVideoInfoHandler,
		newVideoManagerServiceGetVideoInfoArgs,
		newVideoManagerServiceGetVideoInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteVideo": kitex.NewMethodInfo(
		deleteVideoHandler,
		newVideoManagerServiceDeleteVideoArgs,
		newVideoManagerServiceDeleteVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Transcode": kitex.NewMethodInfo(
		transcodeHandler,
		newVideoManagerServiceTranscodeArgs,
		newVideoManagerServiceTranscodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTranscodeStatus": kitex.NewMethodInfo(
		getTranscodeStatusHandler,
		newVideoManagerServiceGetTranscodeStatusArgs,
		newVideoManagerServiceGetTranscodeStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoManagerServiceServiceInfo                = NewServiceInfo()
	videoManagerServiceServiceInfoForClient       = NewServiceInfoForClient()
	videoManagerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoManagerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoManagerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoManagerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoManagerService"
	handlerType := (*videomanager.VideoManagerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "videomanager",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func initUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceInitUploadArgs)
	realResult := result.(*videomanager.VideoManagerServiceInitUploadResult)
	success, err := handler.(videomanager.VideoManagerService).InitUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceInitUploadArgs() interface{} {
	return videomanager.NewVideoManagerServiceInitUploadArgs()
}

func newVideoManagerServiceInitUploadResult() interface{} {
	return videomanager.NewVideoManagerServiceInitUploadResult()
}

func finalizeUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceFinalizeUploadArgs)
	realResult := result.(*videomanager.VideoManagerServiceFinalizeUploadResult)
	success, err := handler.(videomanager.VideoManagerService).FinalizeUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceFinalizeUploadArgs() interface{} {
	return videomanager.NewVideoManagerServiceFinalizeUploadArgs()
}

func newVideoManagerServiceFinalizeUploadResult() interface{} {
	return videomanager.NewVideoManagerServiceFinalizeUploadResult()
}

func queryUploadProgressHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceQueryUploadProgressArgs)
	realResult := result.(*videomanager.VideoManagerServiceQueryUploadProgressResult)
	success, err := handler.(videomanager.VideoManagerService).QueryUploadProgress(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceQueryUploadProgressArgs() interface{} {
	return videomanager.NewVideoManagerServiceQueryUploadProgressArgs()
}

func newVideoManagerServiceQueryUploadProgressResult() interface{} {
	return videomanager.NewVideoManagerServiceQueryUploadProgressResult()
}

func abortUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceAbortUploadArgs)
	realResult := result.(*videomanager.VideoManagerServiceAbortUploadResult)
	success, err := handler.(videomanager.VideoManagerService).AbortUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceAbortUploadArgs() interface{} {
	return videomanager.NewVideoManagerServiceAbortUploadArgs()
}

func newVideoManagerServiceAbortUploadResult() interface{} {
	return videomanager.NewVideoManagerServiceAbortUploadResult()
}

func getVideoInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceGetVideoInfoArgs)
	realResult := result.(*videomanager.VideoManagerServiceGetVideoInfoResult)
	success, err := handler.(videomanager.VideoManagerService).GetVideoInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceGetVideoInfoArgs() interface{} {
	return videomanager.NewVideoManagerServiceGetVideoInfoArgs()
}

func newVideoManagerServiceGetVideoInfoResult() interface{} {
	return videomanager.NewVideoManagerServiceGetVideoInfoResult()
}

func deleteVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceDeleteVideoArgs)
	realResult := result.(*videomanager.VideoManagerServiceDeleteVideoResult)
	success, err := handler.(videomanager.VideoManagerService).DeleteVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceDeleteVideoArgs() interface{} {
	return videomanager.NewVideoManagerServiceDeleteVideoArgs()
}

func newVideoManagerServiceDeleteVideoResult() interface{} {
	return videomanager.NewVideoManagerServiceDeleteVideoResult()
}

func transcodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceTranscodeArgs)
	realResult := result.(*videomanager.VideoManagerServiceTranscodeResult)
	success, err := handler.(videomanager.VideoManagerService).Transcode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceTranscodeArgs() interface{} {
	return videomanager.NewVideoManagerServiceTranscodeArgs()
}

func newVideoManagerServiceTranscodeResult() interface{} {
	return videomanager.NewVideoManagerServiceTranscodeResult()
}

func getTranscodeStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videomanager.VideoManagerServiceGetTranscodeStatusArgs)
	realResult := result.(*videomanager.VideoManagerServiceGetTranscodeStatusResult)
	success, err := handler.(videomanager.VideoManagerService).GetTranscodeStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoManagerServiceGetTranscodeStatusArgs() interface{} {
	return videomanager.NewVideoManagerServiceGetTranscodeStatusArgs()
}

func newVideoManagerServiceGetTranscodeStatusResult() interface{} {
	return videomanager.NewVideoManagerServiceGetTranscodeStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) InitUpload(ctx context.Context, req *videomanager.InitUploadReq) (r *videomanager.InitUploadResp, err error) {
	var _args videomanager.VideoManagerServiceInitUploadArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceInitUploadResult
	if err = p.c.Call(ctx, "InitUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FinalizeUpload(ctx context.Context, req *videomanager.FinalizeUploadReq) (r *videomanager.FinalizeUploadResp, err error) {
	var _args videomanager.VideoManagerServiceFinalizeUploadArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceFinalizeUploadResult
	if err = p.c.Call(ctx, "FinalizeUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUploadProgress(ctx context.Context, req *videomanager.QueryUploadProgressReq) (r *videomanager.QueryUploadProgressResp, err error) {
	var _args videomanager.VideoManagerServiceQueryUploadProgressArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceQueryUploadProgressResult
	if err = p.c.Call(ctx, "QueryUploadProgress", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AbortUpload(ctx context.Context, req *videomanager.AbortUploadReq) (r *videomanager.AbortUploadResp, err error) {
	var _args videomanager.VideoManagerServiceAbortUploadArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceAbortUploadResult
	if err = p.c.Call(ctx, "AbortUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoInfo(ctx context.Context, req *videomanager.GetVideoInfoReq) (r *videomanager.GetVideoInfoResp, err error) {
	var _args videomanager.VideoManagerServiceGetVideoInfoArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceGetVideoInfoResult
	if err = p.c.Call(ctx, "GetVideoInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteVideo(ctx context.Context, req *videomanager.DeleteVideoReq) (r *videomanager.DeleteVideoResp, err error) {
	var _args videomanager.VideoManagerServiceDeleteVideoArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceDeleteVideoResult
	if err = p.c.Call(ctx, "DeleteVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Transcode(ctx context.Context, req *videomanager.TranscodeReq) (r *videomanager.TranscodeResp, err error) {
	var _args videomanager.VideoManagerServiceTranscodeArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceTranscodeResult
	if err = p.c.Call(ctx, "Transcode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTranscodeStatus(ctx context.Context, req *videomanager.GetTranscodeStatusReq) (r *videomanager.GetTranscodeStatusResp, err error) {
	var _args videomanager.VideoManagerServiceGetTranscodeStatusArgs
	_args.Req = req
	var _result videomanager.VideoManagerServiceGetTranscodeStatusResult
	if err = p.c.Call(ctx, "GetTranscodeStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
